### ISSUE TITLE
Document what's needed for Python 3 compatiblity

### ISSUE THREAD

**Issue by lbeltrame** [daler/pybedtools#104]
Unless it's too hard, documenting what is needed would help a lot to encourage even outside contributors to ensure this package is Python 3 compatible.

One thing that comes to my mind: getting rid of ez_setup.py and use newer setuptools.

**Comment by msto** [comment]
Hi,

Is there any news on the port to python 3?

**Comment by daler** [comment]
Yep, this is mostly done. If you're on Linux x64 and using Anaconda, try:

`conda install -c daler pybedtools`

Otherwise, use the `py3` branch from this github repo. I'm trying to get the time to do the final testing for release.

**Comment by msto** [comment]
Awesome news, thanks!

**Comment by daler** [comment]
closing because v0.7.0 has py2/py3 support
