### ISSUE TITLE
field_count() leaks open files

### ISSUE THREAD

**Issue by gpratt** [daler/pybedtools#118]
```
   i = 0
    fields = set([])
    for feat in self:
        if i > n:
            break
        i += 1
        # TODO: make this more efficient.
        fields.update([len(feat.fields)])
    assert len(fields) == 1, fields
    return list(fields)[0]
```

Due to break in line 725 in the field_count function the open iterator isn't closed when the count is returned.  I've got a workaround, and its not an urgent bug to fix, but I'm leaving a note so I don't forget in the future.

**Comment by daler** [comment]
Added test in #264, please reopen if this is still an issue!
