### ISSUE TITLE
merging multiple bed files

### ISSUE THREAD

**Issue by guillermomarco** [daler/pybedtools#125]
Hi!

I need to merge multiple bed files into a single one. I've assumed the best approach to ahieve this using pybedtools would be to concatenate multiple bed file into a single bed object then perform a merge of this object containing all the bed intervals.

Maybe this approach is wrong, but I've assumed it this way because I think bedtools merge only allows one bed as input.

**Comment by krushnach80** [comment]
how do i merge multiple files and keep the strand information as well ?

**Comment by dbolser** [comment]
Have you worked on optimising / parallelising these operations? I wonder if it's done in python or calls out to bedtools?
