### ISSUE TITLE
Counts table in fisher is wrong

### ISSUE THREAD

**Issue by michael-imbeault** [daler/pybedtools#129]
It seems that you updated the output of the fisher wrap, but not the dictionary containing table counts to the new output format.

Example:
 Contingency Table Of Counts
                   |  in -b       | not in -b    |
     in -a | 0            | 7770         |
 not in -a | 833          | 7417582      |

And in results.table:

'table': {'in -a': {'in -b': 7770, 'not in -b': 0},
           'not in -a': {'in -b': 7417582, 'not in -b': 833}}

**Comment by daler** [comment]
Thanks for catching this. Should be fixed now in e6f56956fc338dc11669e82ff17a16974b8826c3
