### ISSUE TITLE
Cannot cat BedTool-obj with different fields

### ISSUE THREAD

**Issue by rolfschr** [daler/pybedtools#133]
Hi,
I want to concatenate two bedfiles, one containing only chrom-start-end, the other containing more information per feature. However, the output obj seems to be "empty" (print(BedTool) yields nothing, saveas() yields an empty file). I am not 100% sure this is a bug or maybe it is intended functionality. In the latter, what would be the workaround? (Maybe I'm just plain wrong here ...)

```python
>>> a = pybedtools.example_bedtool('a.bed')
>>> print(a)
chr1    1       100     feature1        0       +
chr1    100     200     feature2        0       +
chr1    150     500     feature3        0       -
chr1    900     950     feature4        0       +
>>> b = pybedtools.BedTool([('chr2', 10, 20)])
>>> print(b)
chr2    10      20
>>> c = pybedtools.BedTool([('chr3', 20, 40)])
>>> print(c)
chr3    20      40
>>> print(b.cat(c))
chr2    10      20
chr3    20      40
>>> print(c.cat(b))
chr2    10      20
chr3    20      40
>>> print(a.cat(b))

>>> print(a.cat(c))

>>> print(c.cat(a))

>>> b.cat(a)
<BedTool(/tmp/pybedtools.zjPrdn.tmp)>
>>> print(b.cat(a))

>>> # OK, seems impossible to concate b or c with a
>>> # but b & c together is fine
>>> d = pybedtools.BedTool([('chr3', 20, 40, 'name')])
>>> print(d)
chr3    20      40      name
>>> d.cat(c)
<BedTool(/tmp/pybedtools.bqch4W.tmp)>
>>> print(d.cat(c))

>>> # Again empty, only diff I can see is the number of fields for d & c
>>> pybedtools.version.__version__
'0.6.9'
```

(btw: https://pypi.python.org/pypi/pybedtools the links to the doc link to 0.6.8, not 0.6.9 as expected)

**Comment by rolfschr** [comment]
Ok, my bad: one needs to do a.cat(b, postmerge=False) to keep the fields. Or even better: just tell the merge operation to keep the columns: a.cat(b, c=4, o='distinct').

**Comment by daler** [comment]
thanks for the heads-up on docs, they should be 0.6.9 now.
