### ISSUE TITLE
Remote BedTools should throw exception when file not found

### ISSUE THREAD

**Issue by sauliusl** [daler/pybedtools#134]
I am currently trying to get the unit tests running on my fork.
One of them `test_remote_bam`  fails because the file it is trying to fetch does not exist any more (will submit a PR skipping that test later on).
It fails, however, because the streamed iterator returns empty output, rather than throwing an appropriate exception. I believe this masks a problem, and thus I suggest adding this test into the suite, and make it pass:

```python
def test_remote_bam_raises_exception_when_file_doesnt_exist():
    x = pybedtools.BedTool('ftp://ftp-trace.ncbi.nih.gov/this/url/clearly/does/not/exist.bam', remote=True)
    stream = x.bam_to_bed(stream=True)

    assert_raises(IOError, next, stream.__iter__())
```

`IOError` might not be appropriate here though, and perhaps some Network-related exception should be used instead. Currently this test fails as `StopIteration` is thrown which is not right.

**Comment by daler** [comment]
Good call, I'll make those changes and add the test. Also, I'll change the remote BAM URL to use something from the pybedtools github repo itself.

**Comment by daler** [comment]
Also, this shows that I need to set up some sort of periodic testing . . . I've been working on the py3 branch, so no changes to master in 2 months meant no travis-ci builds in 2 months.  Plenty of time for BAMs in the wild to go missing.

**Comment by sauliusl** [comment]
I don't think periodic testing is needed as long as the repo is active (which it is).
I am slightly surprised that test did not fail on your py3 branch -- surely py2 and py3 should have the same tests.

**Comment by daler** [comment]
yeah, py3 branch actually has a lot of broken stuff so at the moment travis-ci is only configured to test master.

**Comment by daler** [comment]
Closing for now. v0.7.0 raises ValueError when trying to connect to remote bam, e.g., 
```
ValueError: Remote BAM no longer supported (since BEDTools does not support it)
```
