### ISSUE TITLE
Strand specific bigwigs

### ISSUE THREAD

**Issue by tharvesh** [daler/pybedtools#142]
Is it possible to convert bam to 2 strand specific bigwig files, if strand orientations are given for strand specific experiments?

**Comment by daler** [comment]
Sure -- see this [biostars answer](https://www.biostars.org/p/64495/#64680) for doing the BAM -> bedGraph -> bigWig conversion.

For separate strands you'll have to split the BAM file ahead of time (e.g., using `samtools view -F 0x010` and `samtools view -f 0x010`).
