### ISSUE TITLE
pybedtools.each breaks on streaming bedtool

### ISSUE THREAD

**Issue by gpratt** [daler/pybedtools#143]
The easiest example I can provide is this:

    import pybedtools
    def test(interval):
        print type(interval)
        return interval

    a = pybedtools.example_bedtool('a.bed')
    a.merge(s=True, stream=True).each(test).saveas()
    a.merge(s=True).each(test).saveas()

If you run that you'll notice that the objects getting passed into the merge after stream is called are unicode, not intervals as we would expect.  Got any ideas on an easy fix?  I'd like to be able to stream in my current code, it should save me a lot of time.

Thanks!

**Comment by daler** [comment]
Thanks, I'll work on fixing the underlying issue here. For now, the quick fix is to convert to `Interval` if needed:

```python
import pybedtools
def test(interval):
    if isinstance(interval, basestring):
        interval = pybedtools.create_interval_from_list(
            interval.strip().split('\t')
        )
    interval.start += 10
    return interval

a = pybedtools.example_bedtool('a.bed')
b = a.merge(s=True, stream=True).each(test).saveas()
c = a.merge(s=True).each(test).saveas()
assert b == c
```

Depending on what you're doing and the size of your files, you might want to watch out for deadlocks -- see the warning section here: http://daler.github.io/pybedtools/topical-iterators.html

**Comment by daler** [comment]
I just made some fixes starting with 0f023db5. You shouldn't need the quick fix I mentioned above if you use these latest updates. 

Can you confirm the latest commits work with your data?

**Comment by gpratt** [comment]
That fixed the bug but introduced another one.  Something in shuffling is broken?

---------------------------------------------------------------------------
BEDToolsError                             Traceback (most recent call last)
<ipython-input-3-f068ca1a6fa2> in <module>()
      1 bedtool = pybedtools.BedTool("/Users/gpratt/ad-hoc/KI2_NoIndex_L002_R1.R07_IMP1_7.polyATrim.adapterTrim.rmRep.rmDup.sorted.peaks.bed")
----> 2 region_dict = CLIP_analysis.assign_to_regions(bedtool)

/Users/gpratt/bioinformatics/yeolab/clipper/clipper/src/CLIP_analysis.pyc in assign_to_regions(tool, clusters, assigned_dir, species, nrand)
    252         offset_dict = get_offsets_bed12(bed_dict[region]['real'])
    253         for i in range(nrand):
--> 254             random_intervals = bed_dict[region]['real'].shuffle(genome=species, incl=bedtracks[region].fn).sort()
    255             random_intervals = fix_shuffled_strand(random_intervals, bedtracks[region].fn)
    256             random_intervals = adjust_offsets(random_intervals, offset_dict)

/Users/gpratt/anaconda/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-macosx-10.5-x86_64.egg/pybedtools/bedtool.pyc in decorated(self, *args, **kwargs)
    773             # this calls the actual method in the first place; *result* is
    774             # whatever you get back
--> 775             result = method(self, *args, **kwargs)
    776 
    777             # add appropriate tags

/Users/gpratt/anaconda/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-macosx-10.5-x86_64.egg/pybedtools/bedtool.pyc in wrapped(self, *args, **kwargs)
    334             stream = call_bedtools(cmds, tmp, stdin=stdin,
    335                                    check_stderr=check_stderr,
--> 336                                    decode_output=decode_output,
    337                                    )
    338 

/Users/gpratt/anaconda/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-macosx-10.5-x86_64.egg/pybedtools/helpers.pyc in call_bedtools(cmds, tmpfn, stdin, check_stderr, decode_output, encode_input)
    376 
    377         if stderr:
--> 378             raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
    379 
    380     except (OSError, IOError) as err:

BEDToolsError: 
Command was:

	bedtools shuffle -incl /Users/gpratt/bioinformatics/yeolab/clipper/clipper/data/regions/hg19_distintron500.bed -i /var/folders/51/gcmm1pl94gg391kh4nr7qz7c0000gn/T/pybedtools.UKpcO1.tmp -g /var/folders/51/gcmm1pl94gg391kh4nr7qz7c0000gn/T/pybedtools.7AJ_Ne.tmp

Error message was:
libc++abi.dylib: terminating with uncaught exception of type std::length_error: basic_string

I'll dig in in a bit and try to clean up that stacktrace so its easier to pinpoint the error.

**Comment by gpratt** [comment]
Running the unit tests on my computer a few of the shuffling tests are erroring out.  Not sure if the new update is related.

**Comment by daler** [comment]
It shouldn't have affected anything in shuffle, and the following still works for me:

```python
import pybedtools
a = pybedtools.example_bedtool('a.bed')
b = pybedtools.example_bedtool('b.bed')
a.shuffle(incl=b.fn, genome='hg19')
```

There are known issues with shuffle on Mac not matching shuffle on Linux (https://github.com/daler/pybedtools/issues/93) due to differences in how the seed is handled. Assuming you're running the unit tests on a Mac, do the shuffle errors look like the seed is set wrong? Or are they failing more dramatically?

**Comment by gpratt** [comment]
Now that you mention it, it might be the seed issue, at least on the unit tests.  

Let me dig into my stack trace for a bit.  I think there might still be an issue with the change.  I'll let you know if it might be a general thing we should worry about.

**Comment by daler** [comment]
For the stack trace issue, can you confirm that `bedtracks[region].fn` in `CLIP_analysis.py` is a string and points to an existing filename?

If you open another terminal and paste the `bedtools shuffle` command reported in the stack trace, do you get the same error?  You can also use `pybedtools.debug_mode(True)` and `pybedtools.settings.KEEP_TEMPFILES = True` to make sure tempfiles hang around after Python exits.

Otherwise, I'd need an example I can play around with to debug.  Sorry for the additional headache.

**Comment by gpratt** [comment]
Odd, I reinstalled the package that CLIP analysis is based off of and it looks like that cleaned up the issue.  

Everything looks like its working go ahead and close this! Thanks for a lot the help.

**Comment by daler** [comment]
OK, good to hear -- I'll keep this open for the moment until the likely-related #145 is resolved too.

**Comment by daler** [comment]
#145 was unrelated; no need to keep this open now.
