### ISSUE TITLE
Pybedtools raises a BedTools error and doesn't create bedtools object on warnings from bedtools

### ISSUE THREAD

**Issue by dgaston** [daler/pybedtools#147]
Recent changes to bedtools raise some warnings on certain VCFs that have an annotation like with a structural variant if SVLEN is not specified. This seems to result in no bedtools object being created due to the warnings. I am working with a VCF file from GATKs DiagnoseTargets where the alt field is <DT>, because this looks like a SV in a VCF file and SVLEN is not specified Bedtools issues a warning that it is setting the default length to 1. That is fine, and if I run just bedtools on its own I get the warnings and then the expected output. However in pybedtools after the error the object is not created.

>>> import pybedtools
>>> targeted_regions = pybedtools.BedTool("/data/Resources/trusight-myeloid-amplicon-track-nochr.bed")
>>> coverage_data = pybedtools.BedTool("TM1_S2.diagnosetargets.vcf")
>>> intersections = coverage_data.intersect(targeted_regions, loj=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dgaston/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
    result = method(self, *args, **kwargs)
  File "/home/dgaston/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 336, in wrapped
    decode_output=decode_output,
  File "/home/dgaston/anaconda/lib/python2.7/site-packages/pybedtools/helpers.py", line 378, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools intersect -loj -b /data/Resources/trusight-myeloid-amplicon-track-nochr.bed -a TM1_S2.diagnosetargets.vcf

**Comment by daler** [comment]
Thanks for reporting this. Would you provide some small example files that reproduce the problem?

**Comment by dgaston** [comment]
I created a gist with a sample BED, VCF, and code snippet: https://gist.github.com/dgaston/fc7267f5a1ee30545b6a

**Comment by daler** [comment]
Thanks, that helped.

pybedtools just needed to be told this is expected output on stderr and nothing to raise an exception for.

Specifically, now if pybedtools sees the string "WARNING" in the first 20 characters of stderr, it will continue on as normal rather than considering it an actual error.

**Comment by dgaston** [comment]
That's what I figured the problem/fix would be. Thanks for the quick fix! Now the coverage report portion of my pipeline should work again :)

**Comment by afrendeiro** [comment]
Hi all,
I'd like to reopen this as the current fix (checking for "WARNING" in the beginning of stderr)[1] is not   allowing commands from bedtools that create stderr without error to finish:
https://github.com/daler/pybedtools/blob/b84386aa36611a2be90d5972029186d4ab36cb89/pybedtools/helpers.py#L423-L434

See here an example of running "nuc" on a fasta file without index:
https://gist.github.com/afrendeiro/47fe73064611bc977271a6f529f33e26

Maybe the default should be to raise only if stderr begins with "Error: "?

**Comment by ccario83** [comment]
Related to this, I'm having issues with forwarded warnings from bedtools inundating stdout. Is there a way to ignore them? Temporarily redirecting stdout to /dev/null doesn't seem to work:
```python 
import os, sys
print "Quiet now"
sys.stout = os.devnull
genome = BedTool("genome.fa")
BedTool("test.bed").sequence(fi=genome)
## Bunch of warning messages
sys.stdout = sys.__stdout__
print "Wake up"
```
Redirecting stderr to /dev/null causes this to hang.

Also tried filtering warnings to no avail:
```python 
import warnings
warnings.filterwarnings('ignore')
```

Any suggestions greatly appreciated!

**Comment by lldelisle** [comment]
Hi,
I had the same issue and I found the solution, thanks to you.
The warnings goes to the standard error not to the standard output.
So:
```
import os, sys
sys.stderr.write("Quiet now\n")
sys.stderr = os.devnull
genome = BedTool("genome.fa")
BedTool("test.bed").sequence(fi=genome)
## Bunch of warning messages
sys.stderr = sys.__stderr__
sys.stderr.write("Wake up\n")
```

**Comment by lldelisle** [comment]
*`os.devnull` did not work I needed to use 
```
sys.stderr = open(tempfile.NamedTemporaryFile().name, 'w')
file_to_open = original_file.intersect(region).fn
sys.stderr.close()
```
