### ISSUE TITLE
slop for both A and B bedpe file 

### ISSUE THREAD

**Issue by crazyhottommy** [daler/pybedtools#148]
Hi,

The current pair_to_pair function only slops for A bedpe file. Could you please add some support for slopping both A and B?

if I read in bedpe file using BedTool() function, bedpe[0] only returns the first interval. 
Is there a reader for bedpe file? 

Moreover, if I want to do pairt_to_pair for multiple bedpe files, how can I do it?
Is there a function like mulitbedIntersection function?

Thanks,
Ming

**Comment by daler** [comment]
Hi Ming - 
pybedtools is a wrapper and extension to BEDTools -- the heavy lifting is done in the separately-maintained [bedtools](https://github.com/arq5x/bedtools2) code. So for your questions about 1) slop in B in `bedtools pairtopair` and 2) using bedpe in `multiintersect`, please post to the [BEDTools mailing list](https://groups.google.com/forum/#!forum/bedtools-discuss) or open an issue in the [bedtools](https://github.com/arq5x/bedtools2) github repo.

For your question about a reader for bedpe format, the answer is yes. Check out [this FAQ](http://daler.github.io/pybedtools/FAQs.html#does-pybedtools-have-a-simple-reader-writer-for-bed-files), or here's a quick example using example BEDPE data that ships with pybedtools:

```python
import pybedtools
filename = pybedtools.example_filename('bedpe.bed')
print(open(filename).read())
# chr1	100	200	chr5	5000	5100	bedpe_example1	30	+	-
# chr9	1000	5000	chr9	3000	3800	bedpe_example2	100	-	-

# Note that only the first read of a pair is accessible via
# `Interval.chrom`, `Interval.start`, and `Interval.stop`.
# But you can access other fields by index:

x = pybedtools.BedTool(filename)
for i in x:
    print('chrom1 is: {0}, chrom2 is: {1}'.format(i[0], i[3]))
# chrom1 is: chr1, chrom2 is: chr5
# chrom1 is: chr9, chrom2 is: chr9
```

**Comment by crazyhottommy** [comment]
Thanks for your reply!

Ming
