### ISSUE TITLE
create_interval_from_list doesn't correctly infer file types.

### ISSUE THREAD

**Issue by gpratt** [daler/pybedtools#151]
Hello, I've noticed an issue with create_interval_from_list.  Inferring bedtools or sam files is bugged and causes bedtools to crash in the case there the name filed is an integer and there are >= 11 columns in the bed file.  

For example:
```
print pybedtools.create_interval_from_list(["chr1", "1197700", "1197758", "0", "0.318355266754715", "-", "foo", "bar", "bam", "baz", "bizzle", "buz", "bis"])
```

exits with the error 

```
OverflowError                             Traceback (most recent call last)
<ipython-input-25-c6efb0702665> in <module>()
----> 1 print pybedtools.create_interval_from_list(["chr1", "1197700", "1197758", "0", "0.318355266754715", "-", "foo", "bar", "bam", "baz", "bizzle", "buz", "bis"])

/home/gpratt/anaconda/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-linux-x86_64.egg/pybedtools/cbedtools.pyx in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9337)()
    575     return s.isdigit()
    576 
--> 577 cpdef Interval create_interval_from_list(list fields):
    578     """
    579     Create an Interval object from a list of strings.

/home/gpratt/anaconda/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-linux-x86_64.egg/pybedtools/cbedtools.pyx in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:8470)()
    626         pyb._bed = new BED(
    627             chrom,
--> 628             start,
    629             stop,
    630             strand,

OverflowError: can't convert negative value to CHRPOS
```

Its because of line 608 in cbedtools.pyx:

```
if (len(fields) >= 11) and isdigit(fields[1]) and isdigit(fields[3]):
```

Which will get confused in this situation and think a bedtool is actually a sam file.  If I've got some time I'll try to submit a fix, otherwise I'll just leave this here so the next person knows whats going on.

**Comment by daler** [comment]
Sorry this has been languishing for so long.  I added a fix to check the strand field; if it's not in ['+', '-', '.'] then assume it's SAM. There are plenty of BED files out there that don't have one of these characters in the 6th field, which will still cause the issue. But I think the only way to really get everything correct is to check the regex listed in the SAM spec's table in section 1.4 for every single line. That would be way slow, and it's still possible to have a pathological BED file match all those fields anyway.

Any other suggestions for improving the detection?

**Comment by gpratt** [comment]
We'll probably always run into edge cases like this.  The strand check will
hopefully make just robust enough.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego
