### ISSUE TITLE
intersection of VCF with BED not working when VCF input is not file to path

### ISSUE THREAD

**Issue by IgorFobia** [daler/pybedtools#157]
After making a Pandas DataFrame compatible with a VCF (BedTools recognizes it as a VCF) I cannot intersect it with a BED file.
The reason is that the filtering is performed after the VCF BedTool object is exported to a file without any VCF header; therefore the shell-command `bedtools intersect` cannot recognize it as a VCF and it gives the following error:

`***** ERROR: illegal character '.' found in integer conversion of string ".". Exiting...`

Here is an example of the command that gave me problems; tDF is a Pandas DataFrame
```
from pybedtools import BedTool

tDF['ID'] = '.'
tDF['QUAL'] = 0
tDF['FILTER'] = 'PASS'
tDF['INFO'] = 'AF=' + tDF['AF'].astype(str)
tDF = tDF[['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO']]


tBT = BedTool.from_dataframe(tDF)

regionBT = BedTool('/path/to/file.bed')


tBT.intersect(regionBT)
```

**Comment by daler** [comment]
Thanks for reporting this. I wasn't exposing enough of the `pandas.DataFrame.to_csv` options, so 0b031c6 fixes this.

The most robust way to do this is to open a file, write the full VCF header to it, and then call the (now-fixed) `BedTool.from_dataframe` with that open filehandle.

Here's a self-contained example that works with the update:

```python
import pybedtools
import pandas

# From 1000 Genomes example
contents = """\
##fileformat=VCFv4.0
##fileDate=20090805
##source=myImputationProgramV3.1
##reference=1000GenomesPilot-NCBI36
##phasing=partial
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AF,Number=.,Type=Float,Description="Allele Frequency">
##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP membership, build 129">
##INFO=<ID=H2,Number=0,Type=Flag,Description="HapMap2 membership">
##FILTER=<ID=q10,Description="Quality below 10">
##FILTER=<ID=s50,Description="Less than 50% of samples have data">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA00001	NA00002	NA00003
20	14370	rs6054257	G	A	29	PASS	NS=3;DP=14;AF=0.5;DB;H2	GT:GQ:DP:HQ	0|0:48:1:51,51	1|0:48:8:51,51	1/1:43:5:.,.
20	17330	.	T	A	3	q10	NS=3;DP=11;AF=0.017	GT:GQ:DP:HQ	0|0:49:3:58,50	0|1:3:5:65,3	0/0:41:3
20	1110696	rs6040355	A	G,T	67	PASS	NS=2;DP=10;AF=0.333,0.667;AA=T;DB	GT:GQ:DP:HQ	1|2:21:6:23,27	2|1:2:0:18,2	2/2:35:4
20	1230237	.	T	.	47	PASS	NS=3;DP=13;AA=T	GT:GQ:DP:HQ	0|0:54:7:56,60	0|0:48:4:51,51	0/0:61:2
20	1234567	microsat1	GTCT	G,GTACT	50	PASS	NS=3;DP=9;AA=G	GT:GQ:DP	0/1:35:4	0/2:17:2	1/1:40:3
"""
with open('1kgenomes.vcf', 'w') as fout:
    fout.write(contents)

# create a bedtool with the original data
vcf = pybedtools.BedTool('1kgenomes.vcf')

# and a bed file to intersect
bed = pybedtools.BedTool('20\t14300\t17000', from_string=True).saveas('ex.bed')

# expected output
non_dataframe = str(vcf.intersect(bed))

# save the header for later
header = ''.join([line for line in open('1kgenomes.vcf') if line.startswith('#')])

# convert to dataframe, skipping comment lines
df = vcf.to_dataframe(comment='#', names=['CHROM', 'POS', 'ID', 'REF', 'ALT',
                                     'QUAL', 'FILTER', 'INFO', 'FORMAT',
                                     'NA00001', 'NA00002', 'NA00003'])

# write the header to file
outfile = 'from-dataframe.vcf'
with open(outfile, 'w') as fout:
    fout.write(header)

    # then provide the open filehandle to .from_dataframe
    vcf_from_df = pybedtools.BedTool.from_dataframe(df, outfile=fout)

# ensure identical output
from_dataframe = str(vcf_from_df.intersect(bed))
assert non_dataframe == from_dataframe
```

**Comment by IgorFobia** [comment]
Thank you for you very quick reaction.

Indeed I did something similar myself: I create a VCF file by writing a
header to a file, and then appending to this file the DataFrame exported as
CSV (see below).

I would be great if a VCF file would be created when a certain parameter is
True (or a path is given); however, I guess that extrapolating the correct
header from the data could be difficult. But maybe bedtools just need a
basic header and description of INFO subfields could be superfluous.

Best regards,

Fabio


        headerS =
'##fileformat=VCFv4.2\n##filedate=20160126\n##INFO=<ID=AF,Number=A,Type=Float,Description="Allele
Frequency">\n##FILTER=<ID=qN,Description="Quality below -1">\n#CHROM  POS
ID  REF ALT QUAL    FILTER  INFO\n'

        temp_output_vcf = '/tmp/hack_to_filter.vcf'

        with open(temp_output_vcf, 'w') as oh:
            oh.write(headerS)
        tDF.to_csv(temp_output_vcf, sep='\t', mode='a', header=False,
index=False)


2016-01-26 18:44 GMT+01:00 Ryan Dale <notifications@github.com>:
