### ISSUE TITLE
Tempfiles not cleaned up when forking

### ISSUE THREAD

**Issue by rolfschr** [daler/pybedtools#159]
I have run the following code on pybedtools 0.7.1/Python 2.7.5

```
#!/usr/bin/python
import pybedtools
import os
import threading
import multiprocessing

os.environ['TMPDIR'] = './'

def main():
    regions = [('chr2', int(1), int(2), 'tag')]
    b = pybedtools.BedTool(regions)

# Doesn't delete tmp bedfile
p = multiprocessing.Process(target=main)
p.start()
p.join()

# Deletes tmp bedfile
#t = threading.Thread(target=main)
#t.start()
#t.join()
```
When using ``multithreading``, the temporary bedfile is not deleted. It is deleted when using ``threading`` (e.g. staying within the same process). I am not sure this is a pybedtools bug or rather expected multiprocessing behaviour.

**Comment by daler** [comment]
Thanks for reporting this and including the example.

The function `pybedtools.helpers.cleanup` is registered to be [run on exit](https://github.com/daler/pybedtools/blob/master/pybedtools/helpers.py#L702) but it looks like it's not getting triggered after exiting the `multiprocess`-created process. After looking into it, this is a [known issue with `multiprocessing`](http://stackoverflow.com/questions/26452713/python-process-which-is-joined-will-not-call-atexit).

I'm not sure there's a general, internal-to-pybedtools solution. But the easy solution in this case is to explicitly call `pybedtools.helpers.cleanup()` in `main()`. So the following won't leave any tempfiles around:

```python
#!/usr/bin/python
import pybedtools
import os
import multiprocessing

os.environ['TMPDIR'] = './'

def main():
    regions = [('chr2', int(1), int(2), 'tag')]
    b = pybedtools.BedTool(regions)
    pybedtools.helpers.cleanup()

p = multiprocessing.Process(target=main)
p.start()
p.join()
```

**Comment by rolfschr** [comment]
Thanks for that quick reply and also for finding a solution. In my specific case, I found that running threads instead of process made things for me easier anyway but I'm happy to learn a bit more about pybedtools!
