### ISSUE TITLE
Get a list/set of snps from a BedTool

### ISSUE THREAD

**Issue by MikeDacre** [daler/pybedtools#165]
This seems like a simple idea, but I can't figure it out. I want to intersect two bed files and then just return a list of SNP IDs (as a frozenset in this case, but any iterable is fine). What is the best way to do that?

Also, would you be interested in adding an iterator component to BedTool to allow simple iteration over the file (essentially like ``each()``). e.g.::

    b = BedTool('dbsnp144.bed.gz')
    for snp in b:
        print('My name is {}'.format(snp[3]))

I recognize that this is a trivial addition that doesn't use bedtools at all, but I still think it would be useful.

**Comment by daler** [comment]
Hmm, this should work and is exactly the kind of thing pybedtools is designed for. Here's a self-contained working example using a file that ships with pybedtools:

```python
import pybedtools
a = pybedtools.example_bedtool('a.bed')
print(a)
for i in a:
    print('chrom is {0.chrom}; name is {0.name}; 6th field is {0[5]}'.format(i))
```
gives
```
chr1	1	100	feature1	0	+
chr1	100	200	feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	+

chrom is chr1; name is feature1; 6th field is +
chrom is chr1; name is feature2; 6th field is +
chrom is chr1; name is feature3; 6th field is -
chrom is chr1; name is feature4; 6th field is +
```

Or more directly what you're asking for, 

```python
frozenset([i.name for i in a])
```
```
frozenset({'feature1', 'feature2', 'feature3', 'feature4'})
```
Does this work for you? If so -- but your original example doesn't -- can you paste the first lines of your example file so I can debug?

**Comment by MikeDacre** [comment]
That works perfectly, thank you. I realize that I just had a bug in my code, and I assumed that the feature hadn't been implemented.

Thanks so much, closing now.
