### ISSUE TITLE
Failed install:  collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by dvklopfenstein** [daler/pybedtools#174]
How might I get the pybedtools install to work? I unsuccessfully did:

```
$ git clone https://github.com/daler/pybedtools.git
$ cd pybedtools
$ git pull
$ sudo python setup.py develop
```
Also, unsuccessful was "pip install pybedtools"

Here is the log when trying to install pybedtools:
[pybedtools_install.zip](https://github.com/daler/pybedtools/files/278346/pybedtools_install.zip)

I was able to Successfully install these after cloning and am using them with no problems:
git clone https://github.com/arq5x/bedtools2.git
git clone https://github.com/samtools/htslib.git
git clone https://github.com/samtools/samtools.git

I am using Cygwin.

**Comment by daler** [comment]
This looks to be a pysam compilation issue -- are you able to install pysam separately?

Also, give [bioconda](https://bioconda.github.io/) a shot which will make things much easier if it works on Cygwin:

```
conda install -c bioconda pybedtools
```

Sorry I can't help with any Cygwin issues though.

**Comment by dvklopfenstein** [comment]
Thank you so much for the quick response. I am eager to use pybedtools. I just tried bioconda (unsuccessfull) and will try pysam separately and get back to you.

I tried bioconda and unfortunately, it did not work out.  Here are the messages:

$ conda install -c bioconda pybedtools
Fetching package metadata: ......
Using Anaconda Cloud api site https://api.anaconda.org
Error: No packages found in current win-64 channels matching: pybedtools

You can search for this package on anaconda.org with

    anaconda search -t conda pybedtools

$ anaconda search -t conda pybedtools
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     bcbio/pybedtools          |    0.6.9 | conda           | linux-64, osx-64
     bioconda/pybedtools       |    0.7.7 | conda           | linux-64, osx-64
                                          : Wraps BEDTools for use in Python and adds many additional features.
     cgat/pybedtools           |    0.6.8 | conda           | linux-64
     daler/pybedtools          |    0.7.2 | conda           | linux-64
     lparsons/pybedtools       |    0.6.4 | conda           | osx-64
                                          : none
Found 5 packages
Using Anaconda Cloud api site https://api.anaconda.org

$ conda install -c bioconda daler/pybedtools
Fetching package metadata: ......
Using Anaconda Cloud api site https://api.anaconda.org
Error: No packages found in current win-64 channels matching: daler/pybedtools

You can search for this package on anaconda.org with

    anaconda search -t conda daler/pybedtools

**Comment by daler** [comment]
I was worried about that -- conda is detecting cygwin as Windows. Unfortunately bioconda doesn't support Windows (though honestly that seems to be the case with most bioinformatics software).

**Comment by dvklopfenstein** [comment]
That is disappointing. I guess I'll just have to run the command-line executables and post-process the resulting files.
