### ISSUE TITLE
Choose tempdir?

### ISSUE THREAD

**Issue by endrebak** [daler/pybedtools#176]
I had managed to fill up a tmpdisk and pybedtools turned out to be the culprit.

Therefore I'd like to store tmpfiles to a slow (but big) disk. Is choosing your own tmpfolder possible?

**Comment by daler** [comment]
Yep, see [`helpers.set_tempdir`](https://daler.github.io/pybedtools/autodocs/pybedtools.helpers.set_tempdir.html)
