### ISSUE TITLE
add wrapper for 'tabix -l'

### ISSUE THREAD

**Issue by nlwashington** [daler/pybedtools#180]
There's a tabix command for listing the indexed chromosomes, but this isn't wrapped in pybedtools.  Can you add this?

**Comment by daler** [comment]
I haven't used `-l` before, that seems useful. I guess a new `BedTool.tabix_chromosomes()` method is most straightforward, as opposed to changing the output type of `BedTool.tabix_intervals()` when passed `l=True`. Any other method name suggestions?

**Comment by daler** [comment]
Added in #264
