### ISSUE TITLE
fetching non-indexed sequence with tabix_intervals throws error

### ISSUE THREAD

**Issue by nlwashington** [daler/pybedtools#181]
When I use the `BedTool.tabix_intervals(goodinterval)` function with a properly indexed region, i get an iterator back.  However, when I try the same thing with a bad interval, i get a value error:

<pre>
badinterval = 'chrBOO:123-456'
features = feature_file.tabix_intervals(badinterval)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pybedtools/bedtool.py", line 618, in tabix_intervals
    results = tbx.fetch(str(interval.chrom), interval.start, interval.stop)
  File "pysam/ctabix.pyx", line 441, in pysam.ctabix.TabixFile.fetch (pysam/ctabix.c:5031)
ValueError: could not create iterator for region 'chrBOO:124-456'
</pre>

I can certainly wrap this function call in a try/except, but without being able to get a list of the indexed chromosomes (see feature request #180), I can't do this sensibly.  

Perhaps instead of throwing this error, it either returns None, or an empty generator?  When I query my file with this same bogus region using tabix on the command line, it just returns nothing back.

**Comment by daler** [comment]
Matching command-line behavior is definitely a good thing. This is a pysam issue, but as you point out it's a quick fix in pybedtools -- I'll add it.

**Comment by daler** [comment]
Addressed in #264
