### ISSUE TITLE
iterative use of tabix_intervals silently fails somewhat predictably

### ISSUE THREAD

**Issue by nlwashington** [daler/pybedtools#183]
i have a relatively large (30G) tabix-indexed bed-like file that i need to extract out a bunch of data based on the contents of another bed file.  when the number of lookup intervals is small (like 5), it is much much faster to iterate using the `BedTool.tabix_interval` functionality rather than `BedTool.intersect`.

however, i've found that trying the same procedure with a list of 500 intervals reliably dies at the same point in the list (item 127 to be exact).  there's nothing wrong with the interval that it dies on, and if i extract out items 110-130 the loop works just fine.  furthermore, i've tried this with other lists, and they all seem to die in the same point in their respective lists.

the resulting behavior is that my program will die during the loop, with no exit status, logging or feedback in any way, even when pybedtools.debug is True.

the overall code looks like:

<pre>
coverage_stats_bed = BedTool(self.combo_coverage_path)  # this is the 30G file
querybed_tabix_coverage = BedTool('', from_string=True)
querybed_coverage_list = list()
lineno = 0
for i in querybed:
    lineno += 1
    print("lineno=%d, i=%s", lineno, str(i))
    if re.sub('chr', '', i['chrom']) in hgbutils.valid_chrs:
        thisstuff = coverage_stats_bed.tabix_intervals(i)         # <----- this is where it dies
        querybed_coverage_list = querybed_coverage_list + list(thisstuff.features())
querybed_tabix_coverage = BedTool(querybed_coverage_list).saveas()
</pre>

fwiw, my ulimit is set to 10K on my local file system, or 1M when run within a docker container.
have you ever heard of this kind of a problem or have any suggestions for how to fix?  is this pysam seg faulting?  is it opening too many tmp files?

**Comment by daler** [comment]
Very strange. Can you provide a minimal reproducible example that I can use to debug?

**Comment by nlwashington** [comment]
also, fwiw, i tried this with the native pysam instead of bedtools, and it can at least loop through the full query
<pre>
import pysam
tbx = pysam.TabixFile(self.combo_coverage_path)
linecount = 0
for i in querybed:
    linecount += 1
    chrom = (i['chrom']).encode('utf-8')     # <-- it seems pysam can't handle unicode strings
    start  = i['start']
    stop = i['stop']
    for row in tbx.fetch(chrom, int(start), int(stop)):
         print ("%d: %s", linecount, str(row))
</pre>

**Comment by nlwashington** [comment]
as for reproducible example, i will see if i can get the same behavior on a smaller tabix'd file, but i'm thinking it might only happen with the large (30G) file.  let me see if i can drum something up.

**Comment by daler** [comment]
OK thanks. And good to know about pysam. There are still some parts of pybedtools that duplicate pysam functionality; I'd like to switch to pysam for all of them.

**Comment by daler** [comment]
I'm still unable to reproduce; please reopen if this is still an issue!
