### ISSUE TITLE
Pysam missing dependency

### ISSUE THREAD

**Issue by jrdemasi** [daler/pybedtools#185]
Hey, sorry to open another issue... But pysam is missing from the dependency list as well.

**Comment by daler** [comment]
I had to remind myself how I was handling setup, and six, pandas, and pysam should be installed (e.g., 
https://github.com/daler/pybedtools/blob/master/setup.py#L322). How are you installing?

**Comment by jrdemasi** [comment]
All of our python modules are installed from source (this is a compute cluster).  Originally I built and sourced cython, six, and pybedtools.  At that point I got an import error for missing pysam.  I built and sourced pysam, then got a numpy import error.  Now I am getting a pandas import error.  Regardless of how it's being built, if they have to be installed to import pybedtools, they are dependencies, right?  Unfortunately not everyone is always going to be using pip or even easy_install, so having an accurate list of dependencies for other environments (like on a compute cluster or other atypical environments) is really important for administrators that have to install/maintain recent versions of the software. Thanks for looking into this, I really appreciate it.

**Comment by kyleabeauchamp** [comment]
I highly recommend looking into conda + bioconda: https://bioconda.github.io/

**Comment by jrdemasi** [comment]
Thanks, @kyleabeauchamp, but very intentionally staying away from any kind of package management.

**Comment by daler** [comment]
Not clear why the setup.py is not installing six and pysam and numpy -- six is specified [here](https://github.com/daler/pybedtools/blob/master/setup.py#L110); pysam [here](https://github.com/daler/pybedtools/blob/master/setup.py#L116). But the testing and building needs to identify these problems. Currently it uses bioconda to set up the env but it should set up a completely bare environment (py2 or py3 alone and nothing else).

**Comment by jrdemasi** [comment]
My exact command to build is as follows:

`mkdir -p /tmp/pack-biof-pybedtools/python2/
/opt/python/2.7.11/bin/python2 setup.py install --prefix='/opt/pybedtools/python2/0.7.8' --root "/tmp/pack-biof-pybedtools/python2/"`

Unconventional, sure, but works fine for the majority of other modules I'm dealing with.

**Comment by daler** [comment]
Sorry for the frustration, I'll fix this ASAP.

**Comment by jrdemasi** [comment]
No worries at all. If I can provide anything to assist please let me know. Thanks again!

**Comment by daler** [comment]
Do you have setuptools installed in the environment this is failing in?

**Comment by daler** [comment]
And does it work in Python 3?

**Comment by jrdemasi** [comment]
@daler -- it was not sourced at the time of trying to build, no, but it is available on the system in question.  But it didn't yell at me or anything, whereas other packages that utilize setuptools tend to complain when trying to import it during the setup/install.  For what it's worth, pybedtools built fine once I had all of the dependencies manually installed (and without setuptools).  No insight on Python 3, as I am trying with 2.7.11.  I can go back and try 3.5.x after I'm finished with the first round if that'd be helpful?

**Comment by daler** [comment]
Looking at setup.py, I think if on py27 and with no setuptools the [`install_requires` are not being added](https://github.com/daler/pybedtools/blob/master/setup.py#L323). Python 3x [should complain](https://github.com/daler/pybedtools/blob/master/setup.py#L44).

Easiest solution would be to require setuptools in setup.py. I'll work on getting some tests going for this. I'm remembering why I moved to conda for everything . . . compiling pysam, numpy, and pandas from scratch for every test run takes forever!

**Comment by jrdemasi** [comment]
Makes sense -- requiring setuptools is probably good, or even adding optional flags to either include or not include numpy, pysam, etc.  Just listing them as clear deps for anyone compiling from source would probably be enough, in my opinion.  Had they been listed I wouldn't have even opened an issue probably, but it looks like I did uncover a true "bug" in that it wouldn't work for someone trying to just install it in a more sane, traditional way.  Can't tell you how great it is as an admin to have found a responsive project owner/maintainer though :-p

**Comment by daler** [comment]
OK, in a bare docker container I confirmed that this was due to a lack of setuptools being installed. The travis-ci tests weren't catching it because the most basic conda env still includes setuptools, and trying to remove it causes the entire env to be removed. Rather than rebuild the entire testing framework to use a bare docker container to test lack of setuptools, I'm instead requiring setuptools for the installation.

I also made pandas fully optional -- you won't be notified to install it unless you try to use one of the functions or methods that require it.

Can you give this a shot now?

**Comment by jrdemasi** [comment]
@daler Sorry, been a busy day.  I will be able to test this out tonight or early tomorrow to provide feedback. Sorry for the delay, given that you scrambled to fix the issue.

**Comment by jrdemasi** [comment]
@daler Can confirm this works as you intend now on python-2.7.3

Thanks
