### ISSUE TITLE
Compilation error during "pip install pybedtools"

### ISSUE THREAD

**Issue by vladsaveliev** [daler/pybedtools#186]
I'm running `pip install pybedtools` and having the following error:

```
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/gzstream.o build/temp.linux-x86_64-2.7/src/bedFile.o build/temp.linux-x86_64-2.7/src/fileType.o build/temp.linux-x86_64-2.7/pybedtools/cbedtools.o -lstdc++ -lz -o build/lib.linux-x86_64-2.7/pybedtools/cbedtools.so
    c++: error: unrecognized command line option '-Wdate-time'
    c++: error: unrecognized command line option '-fstack-protector-strong'
    c++: error: unrecognized command line option '-Wdate-time'
    c++: error: unrecognized command line option '-fstack-protector-strong'
    error: command 'c++' failed with exit status 1
```

gcc version 4.8.5 (Debian 4.8.5-3)

**Comment by daler** [comment]
Sorry, I'm unable to reproduce. I tried a bare Docker image with just the minimum dependencies, as well as separate conda py27 and py35 environments. It worked in all cases.

Here's the Dockerfile I used:

```
FROM ubuntu:14.04
RUN apt-get update && apt-get install -y \
build-essential \
zlib1g-dev \
python-dev \
python-pip
```

Built like this:

```
docker build -t pybedtools-test .
```

And tested like this:

```bash
docker run pybedtools-test gcc --version
docker run pybedtools-test pip install pybedtools
```

Are you able to install via conda (using the [bioconda](https://bioconda.github.io/) channel)?

```bash
conda install --channel bioconda pybedtools
```

**Comment by vladsaveliev** [comment]
It worked pretty well with conda, but conda seems to pull some dependencies like "libgcc" which may have helped to compile it correctly.

Hopefully it's just this machine's issue - never had such error on any other computer.  For my application, I need the pip version, but I can use the docker to run my app on this machine.

Attaching the full log just for the record, 
[pip_install_pybedtools_log.txt](https://github.com/daler/pybedtools/files/413655/pip_install_pybedtools_log.txt)
