### ISSUE TITLE
Test fail under Debian unstable

### ISSUE THREAD

**Issue by mr-c** [daler/pybedtools#193]
Hello,

I'm [packaging pybedtools for Debian](https://bugs.debian.org/851358) and one of the tests is failing for me:

```
======================================================================
FAIL: pybedtools.test.test1.test_issue_156
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcrusoe/src/pybedtools/env/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mcrusoe/src/pybedtools/pybedtools/test/test1.py", line 1976, in test_issue_156
    """)
AssertionError:

```
Any ideas as to what is going on here?

Thanks!

**Comment by daler** [comment]
Looks like this is a BEDTools issue from version 2.25 to 2.26. The current travis-ci tests for pybedtools use BEDTools 2.25, but when I bump it to 2.26, this test (and a couple others) fail. It appears to be a difference in how GFF intervals are handled. I'll open an issue on bedtools.

**Comment by daler** [comment]
Thanks for reporting this, and packaging pybedtools!

**Comment by mr-c** [comment]
Hey @daler , you are welcome and thanks for the quick responce. Since the bug is in the underlying tool I've disabled the test with a link to this issue.
