### ISSUE TITLE
Implementation of shift possible?

### ISSUE THREAD

**Issue by cfljam** [daler/pybedtools#200]
I would like to be able to pythonically use [bedtools shift](http://bedtools.readthedocs.io/en/latest/content/tools/shift.html) to adjust all my intervals by the same  amount. Is this possible or could it be added?

**Comment by daler** [comment]
Certainly. Need to clear my plate before I can get to this. But if you want to give it a shot and submit a PR, I have docs on wrapping a new tool here: https://daler.github.io/pybedtools/topical-wrapping.html

**Comment by cfljam** [comment]
Thanks! Will seriously look at doing this
