### ISSUE TITLE
Creat temp file inside a subdirectory under /tmp/

### ISSUE THREAD

**Issue by mmiladi** [daler/pybedtools#202]
Hi,

It would be really good if the all temporary file pathes aggreagted into a subdirectory of `/tmp/ e.g. `/tmp/pybedtool/` (same as practice done by many tools like Mozilla). Having this reduces the side-effects of pybedtools tmp files on the OS and other programs, specially in the scenarios where many tmp files are created. Currently I am facing the problem where too many tmp files, makes the other programs slow, probably because they need to list the content of /tmp/ main directory which is overwhelmed with the pybedtools temp files.

**Comment by daler** [comment]
Good point. You can currently set this using `pybedtools.set_tempdir`, but using a subdirectory by default would be better.

**Comment by mmiladi** [comment]
Thanks for mentioning the `set_temp` function. By the way, I was wondering why my tmp directory is not cleaned up automatically at the end of sessison. Is the auto clean-up functionality is tested inside ipython (notebook)?

**Comment by daler** [comment]
The `pybedtools.helpers` module registers the `cleanup` function to run at exit [here](https://github.com/daler/pybedtools/blob/master/pybedtools/helpers.py#L709). I don't know how jupyter notebooks handle handle that, and that functionality is not currently tested within notebooks. If you have suggestions on how to work that into the testing framework that would be helpful. In the meantime, I'd suggest manually calling `pybedtools.cleanup` when you're sure you no longer need temp files.

**Comment by daler** [comment]
Closing for now; please reopen if needed.
