### ISSUE TITLE
set_bedtools_path() not effective with  pybedtools.BedTool()

### ISSUE THREAD

**Issue by lonsbio** [daler/pybedtools#222]
Related to #218 , I'm using the master branch with the fix but  I'm still getting the same issue of a `NotImplementedError` (`importlib` fix didn't work for me). 

It's come up for a sorting use case, so the example below uses that, but the reload that should now happen from `helpers.set_bedtools_path()` only seems to work when invoking  `pybedtools.bedtool.BedTool()` rather than  `pybedtools.BedTool()`. I'm not clear on the difference between the two however!  Using `example_filename()` doesn't cause this issue which is why I think it gets through the test cases.
When bedtools is *not* on the path, the first try case will fail:

```python
import pybedtools

a_bed_copy_location = "a_unsorted.bed"
bedtools_location = '/path/to/bedtools/bin/'

# show bedtools path
print("Before set_bedtools_path",pybedtools.helpers.get_bedtools_path())
pybedtools.helpers.set_bedtools_path(bedtools_location)
print("After set_bedtools_path",pybedtools.helpers.get_bedtools_path())

try:
    print("# pybedtools.BedTool")
    bed_file = pybedtools.BedTool(a_bed_copy_location)
    print(bed_file)
    sorted_bed_file = bed_file.sort()
    print("Sorted using pybedtools.BedTool")
    print(sorted_bed_file)
except NotImplementedError:
    print("Cannot sort using pybedtools.BedTool")

print("#####################")


try:
    print("# pybedtools.bedtool.BedTool")
    bed_file = pybedtools.bedtool.BedTool(a_bed_copy_location)
    print(bed_file)
    sorted_bed_file = bed_file.sort()
    print("Sorted using pybedtools.bedtool.BedTool")
    print(sorted_bed_file)

except NotImplementedError:
    print("Cannot sort using pybedtools.bedtool.BedTool")
```

**Comment by daler** [comment]
closed in #223
