### ISSUE TITLE
pair_to_pair ignore strand

### ISSUE THREAD

**Issue by YichaoCaiDBS** [daler/pybedtools#224]
Hi,

I am trying to use pybedtools(0.7.10) pair_to_pair to intersect two BEDPE files. My bedtools version is 2.26.0.
I came across a problem that I can set -is(ignore strand) to True.
The code I am using:
```
import pybedtools
a = pybedtools.BedTool('test_selected.bedpe')
b = pybedtools.BedTool('test_rest.bedpe')
intersect = a.pair_to_pair(b,type="either",is=True)
```
But it turns out that `is` is not applicable, which is a reserved word in python.
```
  File "jumpLoop.py", line 38
    intersect = a.pair_to_pair(b,type="either",is=True)
                                                ^
SyntaxError: invalid syntax
```
Is there any way to set ignore strand to be True?

Thank you so much!

**Comment by daler** [comment]
In general, Python lets you provide additional keyword arguments as a dictionary, where keys are strings, and use the `**` unpacking syntax in the function call. There are several cases in BEDTools where arguments are Python reserved keywords, and in each case the workaround looks like this:

```python
kwargs = {'is': True}
intersect = a.pair_to_pair(b, type='either', **kwargs)
```

Notice the syntax highlighting affects `type` there (which is a Python built-in), but at least it won't give a syntax error like `is`. You could also do this:

```python
intersect = a.pair_t_pair(b, **{'type': 'either', 'is': True})
```

**Comment by YichaoCaiDBS** [comment]
Thank you so much @daler !
