### ISSUE TITLE
a.intersect(b, wao=True) returns invalid BedTool when b has more than 3 columns

### ISSUE THREAD

**Issue by bnelsj** [daler/pybedtools#225]
If you intersect a BedTool with a 4 column BedTool using wao, the result has different field counts depending on if there were hits:
```
a = '''chr1 1084355 1084747 a                  
chr1 1074355 1074747 b'''
b = '''chr1 1084455 1084647 a                     
chr1 1094355 1094747 b'''
a_bed = pybedtools.BedTool(a, from_string=True)
b_bed = pybedtools.BedTool(b, from_string=True)
test_bed = a_bed.intersect(b_bed, wao=True)
test_bed.field_count()
```
Gives:
`AssertionError: {9, 10}`
With these fields:
```
['chr1', '1084355', '1084747', 'a', 'chr1', '1084455', '1084647', 'a', '192']
['chr1', '1074355', '1074747', 'b', '.', '-1', '-1', '', '.', '0']
```
So entry 7 in the last row is empty and extraneous. This is on pybedtools v0.7.10.

**Comment by daler** [comment]
Thanks for reporting this. The results will be dependent on which version of BEDTools you are using. For example, on BEDTools v2.26.0 I'm unable to reproduce. Which version of BEDTools are you running?

**Comment by bnelsj** [comment]
Ah, you're right. I'm on v2.25.0, and bedtools intersect shows the same behavior.

**Comment by daler** [comment]
OK. If you continue to see this issue after updating (and this seems to be a pybedtools issue) please re-open.
