### ISSUE TITLE
Make it possible to configure which bedtools installation to use before importing the pybedtools library

### ISSUE THREAD

**Issue by NeillGibson** [daler/pybedtools#226]
Hi, 

I am using pybedtools on a system where the default bedtools executables are configured to run automatic via a queue system on a cluster. 

This makes it very slow to import something from the bedtools library.

For example `from pybedtools import BedTool` causes a check on all bedtools executables which causes a long list of grid jobs to be started.

I do have the normal bedtools executables on my system, but I can't set those as the system default. 

Is there are way to specify somewhere in a config file which bedtools installation pybedtools should use? Or maybe as a environment variable?

Thank you.

**Comment by daler** [comment]
I guess it depends on the mechanism the cluster is using. Are you able to add the path of your installed version to the beginning of your `$PATH` environment variable so it is found first?

Otherwise, I can add the ability to check for an env var (`PYBEDTOOLS_BEDTOOLS_PATH`, maybe?) and use that at import time.

**Comment by NeillGibson** [comment]
Thank you for the advice. I don't have access to the system path or other system/user environment variables. 

Modifying the path variable in the python script just before the pybedtools imports seems to have fixed the issue. 

```
os.environ["PATH"] = "/tools/bedtools-2.26.0/bin/" + os.pathsep + os.environ["PATH"]
from pybedtools import BedTool
```

**Comment by daler** [comment]
Glad it works. By the way, you could put this in your `.bashrc` to do the same thing, which makes your python code more portable:

```bash
export PATH="/tools/bedtools-2.26.0/bin:$PATH"
```
