### ISSUE TITLE
test_issue_178 fails

### ISSUE THREAD

**Issue by tillea** [daler/pybedtools#227]
Hi,
when trying to build the Debian package of pybedtools I get:

    ======================================================================
    ERROR: pybedtools.test.test1.test_issue_178
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/build/python-pybedtools-0.7.10/.pybuild/pythonX.Y_3.6/build/pybedtools/test/test1.py", line    2108, in test_issue_178
        pybedtools.contrib.bigwig.bam_to_bigwig(fn, genome='dm3', output='tmp.bw')
      File "/build/python-pybedtools-0.7.10/.pybuild/pythonX.Y_3.6/build/pybedtools/contrib/bigwig.py", line 123, in bam_to_bigwig
        p = subprocess.Popen(cmds, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'bedGraphToBigWig': 'bedGraphToBigWig'
    
    ----------------------------------------------------------------------
    Ran 491 tests in 13.519s
    
    FAILED (SKIP=1, errors=1)
    E: pybuild pybuild:283: test: plugin distutils failed with: exit code=1: cd /build/python-pybedtools-0.7.10/.pybuild/pythonX.Y_3.6/build; python3.6 -m nose --attr '!url'

For the moment I have excluded this test from the build but it would be good to have this issue solved.
Kind regards, Andreas.

**Comment by daler** [comment]
Thanks for reporting. These are external compiled tools that are installed as part of the CI testing (https://github.com/daler/pybedtools/blob/master/optional-requirements.txt), but not installed by pybedtools itself.

I'll add a more informative error message, and skip the test if they're not available.

**Comment by daler** [comment]
@tillea can you try https://github.com/daler/pybedtools/pull/228?

**Comment by tillea** [comment]
On Wed, Nov 08, 2017 at 09:46:00PM +0000, Ryan Dale wrote:
> @tillea can you try https://github.com/daler/pybedtools/pull/228?
Successfully tested and uploaded to Debian with this patch.
