### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by bhchiang** [daler/pybedtools#229]
I have this problem where the contents of my bedtools are disappearing.

For instance, I have a bedtool named e, I do:
e=e.each(remove,s) 
where remove is a self defined function.

I then do
print(e)
which gives me the results
chr1    121485434       121485634       1
chr1    121485484       121485684       2
chr1    121485534       121485734       3
chr1    121485584       121485784       4
chr1    121485634       121485834       5
chr1    121485684       121485884       6
chr1    121485734       121485934       7
chr1    121485784       121485934       8
chr1    121485834       121485934       9
chr1    121485884       121485934       10
chr1    144622413       144622613       1
chr1    144622463       144622663       2
chr1    144622513       144622713       3
chr1    144622563       144622763       4
chr1    144622613       144622813       5
chr1    144622663       144622863       6
chr1    144622713       144622913       7
chr1    144622763       144622913       8
chr1    144622813       144622913       9
chr1    144622863       144622913       10

but when I do print(e) one more time, or try to manipulate e after running each, e becomes completely empty. Is this normal behavior?

so print(e) would give me

and len(e) = 0 now.

If I save the bedtool to a separate file using .saveas(), and the reload the saved bed file, I avoid this loss of contents. So I think this might have something to do with the tmp files, but I'm not really sure. Thanks so much!

**Comment by daler** [comment]
Yep, this is normal and expected. `each()` returns a Python generator object. Since the `.saveas()` method returns a BedTool object, you can chain together calls with `saveas()`, choosing when you want to spill to disk.

```python
f = e.each(remove).saveas()
```

More info:
- http://daler.github.io/pybedtools/FAQs.html#i-m-getting-an-empty-bedtool
- http://daler.github.io/pybedtools/topical-iterators.html
