### ISSUE TITLE
Program stalls when intersecting large regions (>10Mb)

### ISSUE THREAD

**Issue by dantaki** [daler/pybedtools#232]
I've noticed that when intersecting large regions (>10Mb), the script stalls and fails to exit. 

```
from pybedtools import BedTool
my_bed = BedTool("my_large_regions.bed")
for entry in my_bed.intersect("my_gene_list.bed", wa=True, wb=True):
    # do stuff here
```
The script stalls with an allocated 32Gb of RAM. 

I've found a work-around for this problem
```
from pybedtools import BedTool
my_bed = BedTool("my_large_regions.bed")
tmp_bed = "tmp_intersect.bed"
my_bed.intersect("my_gene_list.bed",wa=True,wb=True, output=tmp_bed)
with open(tmp_bed,'r') as f:
    for l in f:
        # do stuff here
os.remove(tmp_bed)
```
The work-around executes under 1 minute, compared to running over 48 hours for the first bit of code.

Just wanted to point this out. Not sure if this is a pybedtools issue or an issue with my system (CentOS)

**Comment by daler** [comment]
Hmm, I've never run into this before.

Can you be more specific as to what you're doing in `# do stuff here`? And can you try the first  snippet, but doing `pybedtools.set_tempdir(os.getcwd())` before the `intersect` call? If changing the temp dir speeds it up, that would imply that the default `/tmp` is slow for some reason.

**Comment by dantaki** [comment]
Thanks for the response. 

`#do stuff here` is performing the following:

```
for entry in my_bed.intersect("my_excluded.bed",wao=True):
    entry=tuple(entry)
    locus, ovr = tokenize(entry),int(entry[-1]) #user defined function 
    if ovr==0: continue
    key = locus+(str(entry[6]),)
    if self.excluded.get(key)==None: self.excluded[key]=ovr
    else: self.excluded[key]+=ovr 
```

The script stores the overlaps into a dict. I perform the same operation while reading the file without error. 

I tried using the `pybedtools.set_tempdir(os.getcwd())` but the snippet hangs while the reading from a output file executes quickly. This may be an issue with the server I use and how it defines the default `/tmp`. Sometimes there is considerable lag when there's a lot of I/O operations from many users.

**Comment by daler** [comment]
OK, I'll close for now, but please re-open if you identify anything I can change in pybedtools to help this.
