### ISSUE TITLE
cbedtools.create_interval_from_list crashes with IndexError on blank line

### ISSUE THREAD

**Issue by scnorton** [daler/pybedtools#233]
Root cause of the crash is: https://github.com/daler/pybedtools/blob/63f5a444a03cab7a695c8ceb03416ca21710e980/pybedtools/cbedtools.pyx#L652

If a line in the bed file has fewer than 3 fields (chrom, start, end), then trying to access field 2 will expectedly create an IndexError.  Such is the case when an empty line (i.e. `line == '\n'`) reaches this point - clearly there are 0 usable fields in this case.  The BedTool iterator should explicitly skip blank lines, including those incurred after stripping comments, or invoke some other sanity check to ensure that the minimum number of BED fields exists in a given line.

**Comment by daler** [comment]
Thanks for reporting. Can you verify that https://github.com/daler/pybedtools/pull/234 fixes the issue?
