### ISSUE TITLE
window_maker seems to not obey the -s (step size) option

### ISSUE THREAD

**Issue by JocelynSP** [daler/pybedtools#235]
I want to re-open Issue #81 as I am getting almost the same error. I don't know what the protocol is for re-raising a closed issue, so I'm making a new issue with the same description.
I have posted a complete description of the issue as a comment on #81, but I thought that might not be seen

Regards,
Jocelyn

**Comment by daler** [comment]
Thanks, I saw your comments on #81 as well. I will re-open #81 and close this issue.
