### ISSUE TITLE
narrowPeak support?

### ISSUE THREAD

**Issue by daquang** [daler/pybedtools#236]
Suppose I have a BED narrowPeak file with a line like this:

```
chr3	112395689	112396011	.	1000	.	382.657915780367	-1	4.50383152387804	171
```

The last number, 171, is the local coordinate of the summit. As of now, I cannot seem to recover this number when I load a BED file with the BedTool object and iterate through the intervals.

**Comment by daler** [comment]
You can index into Interval objects; in this case if you want to do anything with the number you'll have to convert from str to int:

```python
x = pybedtools.BedTool('example.narrowPeak')
for i in x:
    summit = int(i[9])

```
More info in the [docs on Interval objects](https://daler.github.io/pybedtools/intervals.html#indexing-into-interval-objects)
