### ISSUE TITLE
Using pandas DataFrame as input for BedTool creation

### ISSUE THREAD

**Issue by fbrundu** [daler/pybedtools#238]
I have a pandas DataFrame with a subset of rows from a specific bedfile. Is it possible to create a BedTool object from this pandas DataFrame without saving it to file?

Thanks,
Francesco

**Comment by daler** [comment]
You can use 

```python
x = pybedtools.BedTool.from_dataframe(df)
```

Under the hood this is actually just saving a temp file that will be cleaned up once you exit Python, but it's a little more convenient than doing it yourself.

By the way, there's also 

```python
y = x.to_dataframe()
```

for going in the reverse direction. In both cases, the operations are still saving to file; I don't know of a good way to get around that.

**Comment by fbrundu** [comment]
Thanks, I don't know why I could not find it by myself.

**Comment by zichenzhang04** [comment]
> You can use
> 
> ```python
> x = pybedtools.BedTool.from_dataframe(df)
> ```
> 
> Under the hood this is actually just saving a temp file that will be cleaned up once you exit Python, but it's a little more convenient than doing it yourself.
> 
> By the way, there's also
> 
> ```python
> y = x.to_dataframe()
> ```
> 
> for going in the reverse direction. In both cases, the operations are still saving to file; I don't know of a good way to get around that.

Thanks!! That helps a lot
