### ISSUE TITLE
multi_intersect confused when using header=True

### ISSUE THREAD

**Issue by Xparx** [daler/pybedtools#239]
I want to use the header argument for multi intersect command. The issue is that any subsequent command fails using the code gives the error below:
```
import pybedtools as bt

bedfiles = ["a.bed", "b.bed"]
x = bt.BedTool()
bfl = []
for bf in bedfiles:
    bfl.append(bt.example_bedtool(bf))

intsect = x.multi_intersect(i=[b.fn for b in bfl], header=True)

print(intsect.head())
```

`MalformedBedLineError: Unable to detect format from ['chrom', 'start', 'end', 'num', 'list', '/home/user/.virtualenvs/default/lib/python3.5/site-packages/pybedtools/test/data/a.bed', '/home/user/.virtualenvs/default/lib/python3.5/site-packages/pybedtools/test/data/b.bed']
`

**Comment by daler** [comment]
Thanks for reporting. The issue here is that multiinter does not output an actual BED file, it's a report of the various intersections.

```python
import pybedtools as bt
import pandas

bedfiles = ["a.bed", "b.bed"]
x = bt.BedTool()
bfl = []
for bf in bedfiles:
    bfl.append(bt.example_bedtool(bf))

intsect = x.multi_intersect(i=[b.fn for b in bfl], header=True)
df = pandas.read_table(intsect.fn)
```
See also https://github.com/daler/pybedtools/issues/113; I'll add a note to the docs for `multi_inter` as a reminder it doesn't give BED output.

**Comment by daler** [comment]
To clarify, multiiner does not spit out a valid BED file **when `header=True`**. If you're OK without the header, another solution here is to use the default `header=False`:

```python
import pybedtools as bt
import pandas

bedfiles = ["a.bed", "b.bed"]
x = bt.BedTool()
bfl = []
for bf in bedfiles:
    bfl.append(bt.example_bedtool(bf))

intsect = x.multi_intersect(i=[b.fn for b in bfl])
intsect.head()
```

gives

```
chr1    1       155     1       1       1       0
chr1   155     200     2       1,2     1       1
chr1   200     500     1       1       1       0
chr1   800     900     1       2       0       1
chr1   900     901     2       1,2     1       1
chr1   901     950     1       1       1       0
```

**Comment by Xparx** [comment]
Thanks for the quick response and fix!
I currently used it with header=False but got confused when switching to True.
