### ISSUE TITLE
Add the choice to change the delimiter when creating a BedTool object when using from_string.

### ISSUE THREAD

**Issue by Seajull** [daler/pybedtools#243]
When creating a BedTool object from a string, all spaces will be converted to tabs.
The problem is i got VCF file with spaces in meta-information line and in INFO fields. I can convert all spaces by a other character but it feel clumsy.

Maybe it can be great to add a option in __init__ function like : 

     def __init_(self, fn=None, from_string=False, remote=False, delimiter=None):

and :

     if from_string:  
            bed_contents = fn 
            fn = self._tmp() 
            fout = open(fn, 'w')  
            for line in bed_contents.splitlines():  
                if len(line.strip()) == 0:  
                    continue 
                if delimiter :
                    line = '\t'.join(line.split(delimiter)) + '\n'
                else :
                    line = '\t'.join(line.split()) + '\n'
                fout.write(line) 
            fout.close() 

So it can be called like this e.g. : 

     BedTool(string, from_string=True, delimiter="@")

**Comment by daler** [comment]
The `from_string` mode is intended to be a quick way of generating examples. For anything more complex, a better way would probably be to write out to a file, e.g., 

```python
with open('ex', 'w') as fout:
    fout.write(string)
BedTool('ex')
```

That said, I'd be happy to accept a pull request that implements this with some examples and tests.

**Comment by daler** [comment]
Closing for now as I'm not sure there's a good use-case for this. But feel free to re-open with an example VCF file that's problematic.
