### ISSUE TITLE
Help optimizing pybedtools code for comparisons

### ISSUE THREAD

**Issue by endrebak** [daler/pybedtools#245]
I am writing up a paper on PyRanges (basically an in-memory version of pybedtools) and I want to optimize the competing libraries as much as I can (while still writing idiomatic, non-icky, non-hacky code).

This is how I time the operation `set_intersection` for pybedtools. `set_intersection` (my name) is what R GenomicRanges calls `intersection`. Since bedtools has no native support for this operation, I expect it to be slower, but it currently takes much much longer than pyranges (20x) which leads me to hope there are some low-hanging fruit here, optimization-wise.

I need to keep the columns 4 and 5 so that strand is the 6. column. Otherwise the s flag in intersection will be a no-op (see https://github.com/arq5x/bedtools2/issues/637): 

```
sc = chip.sort(stream=True).merge(s=True, c=[4, 5, 6], o="distinct")
sb = bg.sort(stream=True).merge(s=True, c=[4, 5, 6], o="distinct")

result = sc.intersect(sb, s=True)
```

**Comment by endrebak** [comment]
I guess I could write it all in one line, but that seems icky to me - the code will be hard to read and error-prone. Is there a way to delay the computation of sc and sb so that they are streamed and to not written to disk before calling intersect?

**Comment by daler** [comment]
As you mention, there's nothing in bedtools to do this, and there's nothing in pybedtools that adds this functionality. You might be able to get away with streaming everything and then only at the very end using `.saveas()` to render to disk, but you might end up with pipe blocking.

20x seems like a lot. Maybe try adding `sorted=True` to the `intersect` call?

Also, you can use pandas-style parenthetical chaining when gluing together lots of operations. For example:

```python
result = (
    chip
    .sort(stream=True)
    .merge(s=True, c=[4,5,6], o='distinct', stream=True)
).intersect(
    bg
    .sort(stream=True)
    .merge(s=True, c=[4, 5, 6], o='distinct', stream=True),
 s=True).saveas()    
```

But that doesn't get around the issue that it's possible, but not elegant or fast, to reproduce that functionality.

**Comment by endrebak** [comment]
Thanks! In the supps I'll discuss how pybedtools is more memory-efficient and faster for most individual steps, but for lots of operations it does pay a price for having to use the disk.
