### ISSUE TITLE
Results of randomstats

### ISSUE THREAD

**Issue by deebhar** [daler/pybedtools#247]
Hi

I used randomstats and am getting results like this:
For one exp: 
self: 372613
other: 80343
actual: 1746
median randomized: 1452.0
normalized: 1.20247933884
percentile: 100.0

For second: 
self: 215250
other: 80343
actual: 644
median randomized: 790.0
normalized: 0.815189873418
percentile: 0.0

Can we get 0 and 100 percentile as result. Can you explain this?
Also is there a way to plot these results?

**Comment by daler** [comment]
Closing as this was answered via email, but copied below in case it's useful for others...

 
> The resolution of the percentiles is limited by the number of iterations. A percentile of 100 means “the actual overlap was higher than 100% of all observed overlaps across all iterations”, in other words very enriched. If you did a million iterations, you might find one that was higher than your actual overlap, in which case the percentile would be 99.9999.
 
> However when we first developed this method there weren’t many other options around. Nowadays I would encourage you to consider GAT, IntervalStats, and StereoGene for assessing enrichment.
