### ISSUE TITLE
autogenerated "pybedtools/version.py" in archive

### ISSUE THREAD

**Issue by smoe** [daler/pybedtools#249]
Hello,
I just came across this issue while committing all "my changes" to a new branch. pybedtools/version.py popped up as changed which it should not to avoid merge conflicts.
You may want to consider to just remove it.
Cheers,
Steffen

**Comment by daler** [comment]
Thanks for reporting; fixed in #264 where I'm now only changing `version.py` based on major/minor/rev in `setup.py` rather than on git commits.
