### ISSUE TITLE
Raise FileNotFoundError for PY3

### ISSUE THREAD

**Issue by gshiba** [daler/pybedtools#255]
Raise `FileNotFoundError` in python 3 instead of `ValueError`.

Example: [`BedTool.__init__`](https://github.com/daler/pybedtools/blob/master/pybedtools/bedtool.py#L458)

I wasn't sure if this was intentional (since technically the file isn't opened yet at time of object creation), but think it's more python3-pythonic to raise the appropriate exception and makes client code easier to read.

I have a fix at [gshiba/pybedtools](https://github.com/gshiba/pybedtools/tree/raise-fnfe), and thanks for this package.

**Comment by daler** [comment]
Thanks @gshiba, these changes are now incorporated into #264.
