### ISSUE TITLE
Error tokenizing dataframes with NaN at the end [Pybedtools 0.7.10]

### ISSUE THREAD

**Issue by Rmulet** [daler/pybedtools#257]
Hi,

When a Pandas dataframe ends with a column that contains NaN values, the method `.from_dataframe()` generates a file that is not compatible with bedtools requirements for tokenization -- probably because the last field is empty in some rows. To the best of my understanding (from [here](https://github.com/daler/pybedtools/issues/238)), the method  `.from_dataframe()` is essentially a wrapper around Pandas `.to_csv()`. Thus, to circumvent this issue I save the data frame using the latter with the option `na_rep=' '`, which leaves no empty fields.

However, I am not sure whether this might be problematic at some other point. In any case, it would be definitely better to be able to use `.from_dataframe()` from Pybedtools directly.

**Comment by daler** [comment]
Thanks for reporting. I think it might be best to use `na_rep='.'` since a lot of the BEDTools programs use that as a placeholder. I'll work out the implications of this and make this fix.
