### ISSUE TITLE
Using Windows, can't install pybedtools with conda, pip or development version

### ISSUE THREAD

**Issue by ifeelsostupid** [daler/pybedtools#263]
'conda install -c daler pybedtools' says the package is not avaliable from the current channels.

'pip install pybedtools' has a FileNotFoundError while running 'python setup.py egg_info'

'python setup.py develop' gives 'fatal error C1038: cannot find include file zlib.h'. I've installed Cygwin and selected everything so I assume all Devel group and zlib items are installed. 

I'm using windows. I'd really aprreciate it if anyone can give me a clue on how to proceed for whichever of these three methods. I have absolutely no knowledge of compling or the computer system and just want to get pybedtools, get it over with, and start with bio stuff...
Thx

**Comment by daler** [comment]
Hi -

Unfortunately, an awful lot of bioinformatics tools are not supported on Windows. It's so much of a headache to develop on Windows and the field moves so fast that we just don't have the bandwidth to support it.

Pybedtools, and its dependencies like bedtools and pysam, are available in the [bioconda](https://bioconda.github.io) channel, but bioconda does not support Windows. Pybedtools itself is completely untested on Windows . . . I'm not sure I'd be able to install it myself nowadays.

Your best bet, and especially the path of least resistance over the long term, would be to use either the Windows Subsystem for Linux (if you're on Windows 10) or a Linux virtual machine. In both of those cases, you could do `conda install pybedtools bedtools -c conda-forge -c bioconda` and everything will work (that's the way I use it and the way it's tested).

Sorry for not having a better answer. I had written the notes about Cygwin in the docs to help Windows users, but I think it will be clearer to state up front that it's not supported.

**Comment by ifeelsostupid** [comment]
Thx a lot anyway.
I am aware that Windows is such a pain... No worries, I think I'm going to give up trying and get a Mac or Linux subsystem next month.
