### ISSUE TITLE
Using the intersect options

### ISSUE THREAD

**Issue by zwardnz** [daler/pybedtools#266]
Hi, I'm trying to learn pybedtools using the intersect and am very new to it.

I want to use the -wb option but can't quite work out how to do this with pybedtools.

At the moment I have:

```
import pybedtools

a = pybedtools.BedTool(en.bed)
b = pybedtools.BedTool('annot.bed')


a.intersect(b)
```
If I do:

`a.intersect(b, -wb )`
I get the error

> 'NameError: name 'wb' is not defined'

**Comment by daler** [comment]
Hi @zwardnz 

Python syntax is different from command-line, so there are some necessary translations that need to happen. In your example above Python is trying to take the negative value of a variable called `wb`.

You'll need to do:

```python
a.intersect(b, wb=True)
```
See https://daler.github.io/pybedtools/intersections.html#intersections. In general, command-line arguments that take no arguments become boolean in Python (as in this example). Other arguments on the command line are strings or ints in Python, for example

```bash
bedtools intersect -a a.bed -b b.bed -d 100 -wb
```
becomes

```python
a.intersect(b, wb=True, d=100)
```

**Comment by zwardnz** [comment]
Brilliant, thanks.

**Comment by akesarwani** [comment]
Thanks!

**Comment by wreckenrodd** [comment]
Bless this thread
