### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by aniram118** [daler/pybedtools#270]
Hey,

I'm trying to intersect 2 BED files, I get the following error while running pybedtools :  

Traceback (most recent call last):
  File "Tester.py", line 1, in <module>
    import pybedtools
  File "/home/anigovin/Tester/pybedtools/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ModuleNotFoundError: No module named 'pybedtools.cbedtools'

Thanks in advance

Best,
A

**Comment by daler** [comment]
Have you installed from source? If so and you're running from the source directory, you can get this error.

You could try running from a different directory or installing via bioconda or pip.

**Comment by aniram118** [comment]
Reinstalled pybedtools with Bioconda and bedtools as well and it seems to work fine now.

Thanks a ton!
