### ISSUE TITLE
Change 4 GPL 2.0-licensed files to GPL 2.0 or later?

### ISSUE THREAD

**Issue by smoe** [daler/pybedtools#271]
Hello,

sorry for this not so very scientific side-show. The files
```
pybedtools/include/bedFile.cpp
pybedtools/include/bedFile.h
pybedtools/include/fileType.cpp
pybedtools/include/fileType.h
```
from 2009 are licensed unter the GPL version 2.0 (exactly) while LICENSE.txt and the remaining files (except for LGPLed pybedtools/include/gzstream.{cpp,h} of another author) are all GPL 2.0 _or_ _later_.  You might possibly feel like homogenizing that and change that license to GPL 2+ for all the GPL-ed files.

**Comment by daler** [comment]
Thanks for pointing this out. After consulting with @arq5x (and as pointed out by #286, following bedtools itself), #360 moves everything to MIT. This is in the newly-released v0.9.0.
