### ISSUE TITLE
Issue with mergeBed collapse function

### ISSUE THREAD

**Issue by magruca** [daler/pybedtools#290]
I am trying to use the mergeBed argument -c to select which columns to keep which requires a second argument -o. When I specify o, I get the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-142-0f44074e2d5f> in <module>
      1 bt_concat = BedTool.from_dataframe(concat)
----> 2 bt_concat_merge = bt_concat.sort().merge(d=100, c=[4,6], o=collapse, s=True)

NameError: name 'collapse' is not defined
```

using the following example line of code:

```
bt_concat = BedTool.from_dataframe(concat)
bt_concat_merge = bt_concat.sort().merge(d=100, c=[4,6], o=collapse, s=True)
```

I'm not sure if I'm passing the argument incorrectly or if this is maybe a bug/feature improvement. Thanks for the help!

**Comment by blaiseli** [comment]
`collapse`, without quotes, will be interpreted as a variable name by python. If you haven't defined a variable with that name, python will raise a `NameError`.

You should probably use `"collapse"` between quotes, to provide a valid character string.

**Comment by daler** [comment]
Sorry for the late reply, as @blaiseli said you'll need to provide the string `"collapse"`:

```python
bt_concat.sort().merge(d=100, c=[4,6], o='collapse', s=True)
```

Please re-open if this does not solve the issue for you.
