### ISSUE TITLE
Can pybedtools controls the resouces used?

### ISSUE THREAD

**Issue by Honchkrow** [daler/pybedtools#292]
Hello,
    I am using pybedtools in my research, but I found it will using all my cores during sorting a large bed files. I did not find parameters about this function。 Is there something that I ignored?
    Thanks!

Shaway

**Comment by daler** [comment]
`pybedtools.BedTool.sort()` uses the command-line `bedtools sort`, which as far as I know is not multithreaded. If this is still an issue, please provide a reproducible example so I can take a look.
