### ISSUE TITLE
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled. Please install a more recent version of BEDTools and re-import to use this method.

### ISSUE THREAD

**Issue by burcakotlu** [daler/pybedtools#294]
I installed pybedtools 0.8.0

################################
import pybedtools

a = pybedtools.example_bedtool('a.bed')
b = pybedtools.example_bedtool('b.bed')
a_and_b = a.intersect(b)
################################

################################
It gives the response below:
Traceback (most recent call last):
File "", line 1, in
File "/home/burcak/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
result = method(self, *args, **kwargs)
File "/home/burcak/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 212, in not_implemented_func
raise NotImplementedError(help_str)
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled. Please install a more recent version of BEDTools and re-import to use this method.
################################

**Comment by blaiseli** [comment]
I think you need to install bedtools separately. See for instance http://daler.github.io/pybedtools/main.html#installation, where a separate command is suggested: `conda install --channel conda-forge --channel bioconda bedtools htslib`

**Comment by daler** [comment]
Please re-open if installing bedtools does not solve the issue.
