### ISSUE TITLE
missing pybedtools.contrib.plotting module

### ISSUE THREAD

**Issue by einanf** [daler/pybedtools#298]
Hi,
I am installing pybedtools using conda with the following commands:

conda install --channel conda-forge --channel bioconda pybedtools

I am doing this inside a virtual env using conda while making sure all the requirements are found (python 3.6, bedtools, gcc). I tried installing a few times, in different environments and the the installation seems fine but I can't find the pybedtools.contrib.plotting module.

Is there something that I don't understand?
thanks,
Einan

**Comment by daler** [comment]
Thanks for reporting and sorry about the delay. Perhaps you need to make sure matplotlib is installed? Here's how I tried to reproduce:

```bash
conda create -n tst --channel conda-forge --channel bioconda pybedtools
source activate tst
python -c 'import pybedtools.contrib.plotting'
```

gives the following error about not having matplotlib, which is an optional requirement:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda3/envs/tst/lib/python3.7/site-packages/pybedtools/contrib/plotting.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

The solution is to install matplotlib in the same environment:

```bash
conda install -n tst --channel conda-forge --channel bioconda matplotlib
```

and then it works:

```bash
source activate tst
python -c 'import pybedtools.contrib.plotting'
```
