### ISSUE TITLE
undefined symbol in cbedtools.so when importing pybedtools

### ISSUE THREAD

**Issue by imk1** [daler/pybedtools#302]
I just installed pybedtools version 0.8.0.  I then tried importing pybedtools and got the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ikaplow/anaconda2/lib/python2.7/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /home/ikaplow/anaconda2/lib/python2.7/site-packages/pybedtools/cbedtools.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

Do you know how I might be able to fix this?  Thanks so much!

**Comment by daler** [comment]
Thanks for reporting and sorry about the delay. If you haven't yet resolved this, can you describe how you installed pybedtools?

**Comment by imk1** [comment]
pybedtools is now working for me, and I cannot remember how I fixed it.  I do know that, since 11/18, I upgraded bedtools to version 2.29.1, but I am not sure if that's what solved the problem.  Thanks for getting back to me!

**Comment by yang-dongxu** [comment]
Hi, I meet same problem now. When I try to import pybedtools in python ,it raises errors:  
`Python 3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybedtools
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/ydx/anaconda3/lib/python3.8/site-packages/pybedtools/__init__.py", line 9, in <module>
from .cbedtools import (
ImportError: /home/ydx/anaconda3/lib/python3.8/site-packages/pybedtools/cbedtools.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
>>>`
python version: 3.8.8
bedtools version: v2.30.0
pybedtools version: 0.8.2

pybedtools are installed by `pip install pybedtools`

Thanks!

**Comment by jhliu17** [comment]
Got the same error. Did you guys find any solution? Thanks for your help!
