### ISSUE TITLE
import error on bedtools from pybedtools

### ISSUE THREAD

**Issue by rthapa26** [daler/pybedtools#316]
Hi,

I am getting the following error. Do you have any suggestions? I would appreciate it.

>>> from pybedtools import BedTool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BedTool' from 'pybedtools' (unknown location)

**Comment by blaiseli** [comment]
My guess is that your pybedtools installation is incomplete. How did you install it? Try to uninstall and re-install.

**Comment by daler** [comment]
@rthapa26 if you're still having issues with this, please re-open with some more info on how you installed and I'll take a look.

**Comment by blaiseli** [comment]
@raerose01 There were probably more error messages or warnings than just "Failed building wheel for pybedtools".
Maybe this can help identifying more precisely what the problem is.
