### ISSUE TITLE
Automatically try to run cythonize when needed while installing from source

### ISSUE THREAD

**Issue by blaiseli** [daler/pybedtools#317]
A package of mine has pybedtools as a dependency, and apparently needs  a more recent version than the one available on pypi (see https://github.com/daler/pybedtools/issues/253#issuecomment-577231520).

I therefore tried to specify a git repository in the `install_requires` section of my `setup.py` (here using the fork where I implemented the fix):

```
    install_requires=[
         "pysam",
         "pybedtools @ git+https://github.com/blaiseli/pybedtools.git@fix_missing_headers",
         # "pybedtools",
     ]
```

However, the installation of the requirements fails due to the absence of the `Cython-generated file 'pybedtools/cbedtools.cpp'`.

The same error occurs when trying to use pip to install pybedtools directly from git (`python3.8 -m pip install --verbose git+https://github.com/daler/pybedtools.git@master`).

Here is the error:

```
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/local/scratch/pip-req-build-axm6s0tt/setup.py", line 239, in <module>
      setup(
    File "/pasteur/homes/bli/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pasteur/homes/bli/.local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/pasteur/homes/bli/local_tars/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/local/scratch/pip-req-build-axm6s0tt/setup.py", line 170, in build_extensions
      raise Exception(
  Exception:
                          Cython-generated file 'pybedtools/cbedtools.cpp' not found.

                          Please install Cython and run

                              python setup.py cythonize


  ERROR: Failed building wheel for pybedtools
```

This can be solved by  adding `--global-option="cythonize"` to the pip install options, **but only if no further dependencies are pulled in** (because the option would apply to them  too, resulting in a failure to install them). pip developers will likely not provide an option to avoid the installation of the dependencies (https://github.com/pypa/pip/issues/7218).

Another issue with this approach is that this is anyways not supported in the `install_requires` section of my `setup.py` (see https://stackoverflow.com/q/58379905/1878788).

Having cythonization automatically done when needed would greatly help me getting my current work done (i.e. deploying my library when I need it).

**Comment by blaiseli** [comment]
@daler I tried to implement this by modifying `setup.py` in https://github.com/daler/pybedtools/pull/318.

The idea is to run `cythonize` on .pyx files corresponding to missing .cpp files instead of just raising an error.

However, I'm far from understanding the possible consequences of the modifications I did. Hopefully you will spot better than me potential issues with this way of doing.

**Comment by daler** [comment]
Apologies for not getting th@blaiseli your changes in #318 look reasonable, and the current tests do test building a source package and installing that ([see here](https://github.com/daler/pybedtools/blob/master/condatest.sh#L40-L47)).

Do your changes here address the original issues you were having? And is there a good test to add to ensure it works for your use-case?

**Comment by blaiseli** [comment]
Hi @daler Regarding the present issue, I think a good test would be to try to install from the git repository:
```
pip install git+https://github.com/daler/pybedtools.git@master
```

But I guess something else than "master" should be used, in order to test the relevant commit.
I don't know how doable this is.

Regarding the original issues, do you mean the ones reported in https://github.com/daler/pybedtools/issues/253 ? If so, a good test might be to check that `bedFile.h` is among the output of `pybedtools.helpers.get_includes()`

**Comment by blaiseli** [comment]
Hi @daler , any updates regarding merging #318 ?

**Comment by daler** [comment]
@blaiseli sorry it has taken so long to get to this, but your changes are now in v0.8.2 which is in PyPI and should hit bioconda soon as well. Can you see if this now works for your use-case?

**Comment by blaiseli** [comment]
@daler It seems the problem is solved. At least, I'm able to install from git without issues regarding missing .cpp files. Thanks.
