### ISSUE TITLE
error reading unicode symbols in the vcf.gz file

### ISSUE THREAD

**Issue by naumenko-sa** [daler/pybedtools#319]
Hello @daler!

Thanks for developing and maintaining pybedtools!

We discovered a bug when running pybedtools in bcbio: https://github.com/bcbio/bcbio-nextgen/issues/3078

test.py:
```
import pybedtools

vrn_file = "small.vcf.gz"
spliceslop = "S10SJ.out-minimized-padded.bed"
bt = pybedtools.BedTool(vrn_file).intersect(spliceslop, wa=True, header=True, v=True).saveas("out.bed")
```
bed and vcf files are here: 
https://drive.google.com/open?id=1p1EuXxU2X7280dzKScohW_JWF55B16Xn

error message:
```
Traceback (most recent call last):
  File "test-error.py", line 5, in <module>
    bt = pybedtools.BedTool(vrn_file).intersect(spliceslop, wa=True, header=True, v=True).saveas("out.bed")
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pybedtools/bedtool.py", line 3134, in saveas
    compressed=compressed)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pybedtools/bedtool.py", line 1289, in _collapse
    out_.writelines(in_)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 6389: invalid continuation byte
```

we think this clinvar record triggers the issue:
`clinvar_disease_name=Ch�diak-Higashi_syndrome`

What do you think would be the best approach to tackle this issue?
maybe adding `errors=ignore` to 
https://github.com/daler/pybedtools/blob/master/pybedtools/bedtool.py#L1406
as recommended here: 
https://stackoverflow.com/questions/1883604/reading-utf-8-characters-from-a-gzip-file-in-python/19794943#19794943

Thanks!
Sergey

**Comment by daler** [comment]
Thanks for reporting. If you can propose a solution with a test that includes that line in a PR, that would help greatly.
