### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode

### ISSUE THREAD

**Issue by mgalardini** [daler/pybedtools#322]
Hi, thanks for the great library. When doing the following operation in python 3.8, a runtime warning is raised:

```
>>> import pybedtools
>>> import tempfile
>>> tmp_bed = tempfile.NamedTemporaryFile()
>>> test = pybedtools.BedTool(tmp_bed.name)
>>> test.sort()
/home/mgalactus/minimamba/envs/pyseer/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
```

I found [this thread](https://bugs.python.org/issue32236) with some more details on why this warning is now raised. [This seems the line](https://github.com/daler/pybedtools/blob/3eaee6204ec95a364a7ad39ff5f01d00f616957a/pybedtools/helpers.py#L426) where the warning is raised.

**Comment by daler** [comment]
@mgalardini this should be fixed as of #324 -- hope to have a release sometime soon.

**Comment by Jeff1995** [comment]
Also seeing this warning. Glad that it has been fixed, but when will there be a new release?

**Comment by roni-fultheim** [comment]
Same here
