### ISSUE TITLE
Pypi version discrepancies.

### ISSUE THREAD

**Issue by DriesSchaumont** [daler/pybedtools#331]
Hello,

While trying to hunt down the source of some warnings, I noticed that this issue was already discussed here: #322 
After updating my pybedtools version (I installed using pip), I am still encountering the warnings. Looking at [the code](https://files.pythonhosted.org/packages/bf/14/152220f39cda6b9b72810eeed103c6ec78422429adabe3aafc3eaf6feb40/pybedtools-0.8.1.tar.gz) on pypi, `BUFSIZE` is set to `1` on line 23 in pybedtools/helpers.py. However, on the master branch I find https://github.com/daler/pybedtools/blob/082c971598c15c134716ee704fb97fae442e66db/pybedtools/helpers.py#L28

From what I understand, both the code on pypi and here on github are version 0.8.1.
https://github.com/daler/pybedtools/blob/082c971598c15c134716ee704fb97fae442e66db/pybedtools/version.py#L3

Is the code on master not officially released yet? Is the version number on pypi incorrect?

Thanks in advance!

**Comment by daler** [comment]
Thanks for reporting. v0.8.2 is now on PyPI - can you see if this works for you?

**Comment by DriesSchaumont** [comment]
Yes, everything seems to be working! Thank you.
