### ISSUE TITLE
python3.8 - runtime warning

### ISSUE THREAD

**Issue by roni-fultheim** [daler/pybedtools#340]
When intersecting using python3.8.5 and latest version of `pybedtools`, I am getting this warning: 
`RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used`

If possible, can this be fixed?
Thank you

**Comment by daler** [comment]
Thanks for reporting. This should be addressed in v0.8.2, now on PyPI. Would you please check to see if this corrects the issue?

**Comment by roni-fultheim** [comment]
I installed pybedtools using conda,is the new version available on conda as
well? Thank you

**Comment by daler** [comment]
Yes -- it's on bioconda as well.

**Comment by roni-fultheim** [comment]
Thank you. Worked.
Also much faster, thanks!

**Comment by daler** [comment]
Not sure I can explain any speed differences, but I'm glad it's working.
