### ISSUE TITLE
remove_invalid not removing entries with start and stop negative

### ISSUE THREAD

**Issue by blaiseli** [daler/pybedtools#343]
I wanted to shift coordinates in a bed file via pybedtools.

Here is `test_shift.py`:

```python
from pybedtools import BedTool

def shift_bed_m5(bed):
    """
    Shift bed interval coordinates by minus 5.
    """
    bed.start -= 5
    bed.stop -= 5
    return bed

bed_tuples = [
    ("I", "0", "10"),
    ("I", "20", "25")]
bed_lines = ["\t".join(bed_tuple) for bed_tuple in bed_tuples]
bed_string = "\n".join(bed_lines)

a = BedTool(bed_string, from_string=True)
print("a")
print(a)

a_prime = a.remove_invalid()
print("a_prime")
print(a_prime)

b = a.each(shift_bed_m5)
print("b")
print(b)

c = b.remove_invalid()
print("c")
print(c)

```

And here is what happens when I run this script:

```
$ ./test_shift.py
a
I       0       10
I       20      25

a_prime
I       0       10
I       20      25

b
I       -5      5
I       15      20

c

```

`c` seems empty, but the second line seems valid, so it should not have been removed.

(I'm using version 0.8.2)

**Comment by blaiseli** [comment]
(It would be nice to have a `check_invalid` method, giving diagnostics about invalid lines.)

**Comment by blaiseli** [comment]
I tried a simple fix here: https://github.com/blaiseli/pybedtools/tree/issue-343

(Using `if 0 <= feature.start <= feature.stop` instead of `if feature.start <= feature.stop` in `remove_invalid`)

However, it does not seem to have any effect.

**Comment by blaiseli** [comment]
I think I have a clue: negative values are overflowed. If I insert printing instructions to show the values of start and stop I get values such as `4294967285`.

**Comment by daler** [comment]
@blaiseli thanks for reporting this, and sorry for the lengthy lag time. The quick fix would be to insert a `.saveas()` to make sure that `.remove_invalid()` is working on a file-based BedTool object.

E.g., using your example above, change:

```python
final = bt.each(shift_bed, s).remove_invalid().sort()
```

to

```python
final = bt.each(shift_bed, s).saveas().remove_invalid().sort()
```

But edf4b33 should remove the need to do that in the future.
