### ISSUE TITLE
BEDtools can handle more than 510 files at a time

### ISSUE THREAD

**Issue by leeleavitt** [daler/pybedtools#354]
I needed this function to work on 1536 vcf files. 

My testing involved using the original BEDtools. This was able to handle all 1536 files at once. 

I then commented out `bedtools.py` lines 340 to 350 and reran my code. for all 1536 vcfs. `pyBedTools` handled this beautifully, although time to complete was 23.6 second compared to the originals 8.6 seconds.

**Comment by daler** [comment]
Addressed in v0.9.1
