### ISSUE TITLE
POS-field in VCF files and intervals derived from them

### ISSUE THREAD

**Issue by DRL** [daler/pybedtools#355]
Hi,

I am confused. In the [documentation](https://daler.github.io/pybedtools/intervals.html?highlight=conventions#bed-is-0-based-others-are-1-based) you state:

> The value in `Interval.start` will always contain the 0-based start position, even if it came from a GFF or other 1-based feature.

So why is the VCF parser treating the POS field like this:

https://github.com/daler/pybedtools/blob/ffe0d4bd2f32a0a5fc0cea049ee73773c4d57573/pybedtools/cbedtools.pyx#L678-L679

as opposed to this line (for GFF):

https://github.com/daler/pybedtools/blob/ffe0d4bd2f32a0a5fc0cea049ee73773c4d57573/pybedtools/cbedtools.pyx#L691

AFAIK, VCF positions in POS-field are 1-based and therefor should be treated by the parser in the same way as GFF files

```
start = int(fields[1]) - 1
end = int(fields[1]) 
```

Operations (intersections/etc) work as expected, but the statement in the documentation feels wrong since in the case of VCF intervals `Interval.start` lists the 1-based coordinates.

Please explain.

cheers, 

dom

**Comment by daler** [comment]
Yep, you're totally right. I had no tests for this, and it has gone unreported for a decade now!

In https://github.com/daler/pybedtools/pull/359/commits/8a8997c7c77e6b5ec0bcc4f8bbe2ae4fb5a56aaf this is now fixed. Thanks for reporting.
