### ISSUE TITLE
pybedtools from conda use version 2.26 not 2.3

### ISSUE THREAD

**Issue by udiland** [daler/pybedtools#371]
Hi,
I want to use the 'getfasta' with 'nameOnly' parameter.
I get the error: *****ERROR: Unrecognized parameter: -nameOnly *****
The output also show that the version of bedTools use is Version: v2.26.0, so there is no such argument.
Is there a way to get pybedtools with Version 2.3? (this is what the online manual show)
Thanks,

**Comment by udiland** [comment]
I now see that this happen only when I run in pycharm ide with remote interpreter to a server with conda environment but when I run the code directly in the server it give the expected results

**Comment by daler** [comment]
Seems like a path issue with pycharm on remote rather than a pybedtools issue then?

**Comment by udiland** [comment]
Looks like it, couldn't figure out exactly what is is going on. Thanks.
