### ISSUE TITLE
Missing arm64 MacOS wheel packages

### ISSUE THREAD

**Issue by Kentalot** [daler/pybedtools#375]
It'd be nice to include this distribution in pypi.  Thanks!

**Comment by aaronwtr** [comment]
Bumping this issue, running in to the same problem when trying to 
`conda install -c bioconda pybedtools`. 

I get the following error: 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - pybedtools

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by daler** [comment]
Regarding the conda package, this is an issue with with entire bioconda channel, not just pybedtools (pybedtools is one of 8000+ packages on bioconda).

The resources, expertise, and volunteer time do not exist yet to re-build everything in the bioconda channel for this architecture.

Separately, I do not currently have an arm64 machine available to build a wheel on pypi but will build one when I can.

**Comment by aaronwtr** [comment]
Gotcha, thanks for the update! 

For now, I managed to fix my issue by installing pybedtools via pip and then installing bedtools separately and adding it to the path, in case that might help anyone running into a similar problem.

**Comment by daler** [comment]
arm64 builds are still pending for bioconda many months later...as this is not a pybedtools-specific issue, closing this issue.
