### ISSUE TITLE
Support Python 3.10 and 3.11

### ISSUE THREAD

**Issue by WouterVH** [daler/pybedtools#383]
Trying to install pybedtools via conda/mamba in a python 3.11 environment.

It tries to install pybedtools v0.8.2, while 0.9 is released.
Is there a specific reason to pin to <3.10?   (untested does not imply broken)

```
> mamba  install --channel conda-forge --channel bioconda pybedtools 

Looking for: ['pybedtools']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
bioconda/noarch                                      4.2MB @   4.3MB/s  1.0s
bioconda/linux-64                                    4.5MB @   3.4MB/s  1.4s

Pinned packages:
  - python 3.11.*

Could not solve for environment specs
Encountered problems while solving:
  - package pybedtools-0.8.2-py39h39abbe0_1 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by daler** [comment]
There's nothing in pybedtools that restricts to Python versions. On the bioconda channel, only up to Python 3.10 is supported -- we're not building for 3.11 yet for any packages.

(see [here](https://anaconda.org/bioconda/pybedtools/files) for py310 pybedtools packages)

Looks like you're trying to install into an environment that already has 3.11 pinned? I actually wouldn't expect any Python packages from bioconda with compiled extensions to be installable in that environment. 

If you could provide a requirements.txt or env.yml file that reproduces this in a new env, I could try troubleshooting.
