### ISSUE TITLE
pybedtools intersect error

### ISSUE THREAD

**Issue by katelynmullen** [daler/pybedtools#389]
Hi, I'm trying to intersect 2 bed files and getting the following error:

BEDToolsError: 
Command was:

	bedtools intersect -a /tmp/pybedtools.5zkx6wsw.tmp -loj -b /tmp/pybedtools.wfouqili.tmp

Error message was:
***** ERROR: illegal number ".". Exiting...

I checked both of my input files, and I do not see the string "." in either of my input files. Attaching both files for reference.
[pybedtools_troubleshooting.txt](https://github.com/daler/pybedtools/files/11519262/pybedtools_troubleshooting.txt)
[best.bbc.ucn.txt](https://github.com/daler/pybedtools/files/11519290/best.bbc.ucn.txt)

**Comment by daler** [comment]
This looks like a BEDTools error rather than pybedtools, but do you get the same error if you remove the header from these files?
