### ISSUE TITLE
bedtools intersect reported incorrect interval intersection

### ISSUE THREAD

**Issue by leon945945** [daler/pybedtools#392]
Hi, I took use of pybedtools to get the interval overlaps of one vcf file and one bed file with `vcf_bed.intersect(SWOcds, header = True, wao = True)`, but it reported some results with no intersection.

> V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3173351 3173993 Cs_M1_003540    .       -       642
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3174481 3175396 Cs_M1_003540    .       -       915
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3191365 3192793 Cs_M1_003550    .       +       1428
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3229242 3230682 Cs_M1_003560    .       +       1440
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3273563 3275003 Cs_M1_003580    .       +       1440
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3304508 3308075 Cs_M1_003590    .       -       3567
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3318749 3319073 Cs_M1_003600    .       -       324
V-M1    3172513 pbsv.SPLIT.DUP.22       T       <DUP>   .       PASS    SVTYPE=DUP;END=3435071;SVLEN=262558;NotFullySpanned     GT:AD:DP:SAC    0/0:23,0:23:10,13,0,0   0/0:19,0:19:7,12,0,0    0/1:31,6:37:9,22,2,4    0/0:36,0:36:14,22,0,0   0/0:17,0:17:5,12,0,0    0/0:19,0:19:6,13,0,0    V-M1    3322917 3323079 Cs_M1_003600    .       -       162

Do you know why the results were like this? Thank you.

**Comment by daler** [comment]
Can you check if your file(s) are tab-delimited? Hard to tell from the formatting of the issue description. If you can attach a file here that reproduces the error, that would be best.

**Comment by dbolser** [comment]
Close as `can't reproduce`?

**Comment by daler** [comment]
@leon945945 please reopen if this is still an issue.
