### ISSUE TITLE
Cythonizing files requires `language_level=2` to be set in cythonize()

### ISSUE THREAD

**Issue by lbeltrame** [daler/pybedtools#393]
The most recent versions of Cython moved from 2 to `3str`, and that breaks the build in various ways.

Context for some of the issues that arise: https://stackoverflow.com/questions/56115159/pxd-relative-cimport-works-for-language-level-2-but-not-for-3

**Comment by daler** [comment]
thanks @daz10000 and @lbeltrame -- can you try v0.9.1?

**Comment by daler** [comment]
Seems to be working according to the related #387, so closing this one too (though @lbeltrame if you hit issues please reopen).

**Comment by lbeltrame** [comment]
I'm currently on holiday, will test in a couple weeks and report back.
