### ISSUE TITLE
"fastaFromBed"  error

### ISSUE THREAD

**Issue by franjmt** [daler/pybedtools#396]
Hi,
I am trying to implement getfasta from bedtools in my python script. but keep getting an error:

`coordinates_bed = BedTool(os.path.join(bed_file_dir,'AAMDC_transcript_1.bed'))`
`sequence = coordinates_bed.sequence(fi=genome_fasta, name=True)`

I get the error: 
NotImplementedError: "fastaFromBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

**Comment by daler** [comment]
As the error suggests, bedtools is not found on the path. Have you installed bedtools and is it on your path?

**Comment by anatori** [comment]
I'm having the same problem. I used `pybedtools.helpers.set_bedtools_path("<correct_path>")` as well as checked that i installed bedtools properly but I still get the same error.

**Comment by daler** [comment]
@franjmt please reopen if this is still an issue.
