### ISSUE TITLE
how to mask gap regions for randomization?

### ISSUE THREAD

**Issue by yangsui0122** [daler/pybedtools#402]
Hi there,
I was wondering if I have two files, **a.bed** and **b.bed**, how can I randomize **a.bed** and intersect it with **b.bed** on certain chromosome and mask the **centromere** and **gaps** by using pybedtools.BedTool.randomintersection()?
Thanks,
YS

**Comment by daler** [comment]
This is not currently supported, but happy to take pull requests to implement this.
