### ISSUE TITLE
total_coverage giving a incorrect value

### ISSUE THREAD

**Issue by duartemolha** [daler/pybedtools#409]
Hi... 
I wonder if you can help me with this.
I have tested this with 
pybedtools=0.10.0 and bedtools v2.31.0

```python
from pybedtools import BedTool

string_of_intervals='1\t1199\t1800\tENST000001\t0\t+\n1\t1299\t1900\tENST000002\t0\t+\n'
value = BedTool(string_of_intervals, from_string=True).sort().merge().total_coverage()  
print(value)
#value printed our is 701
```

this could be calculating the length of the merged interval created
the merged interval is 
1    1199    1900

since bed files use zero-based half-open intervals intervals this should correspond to an interval of length 700 bp, however total_coverage method produces 701

Can you please explain if I am missing something?

Many thanks

Duarte

**Comment by daler** [comment]
One commonly-cited benefit of using 0-based, half-open intervals is that length calculations don't require an additional step and the length is a straightforward `stop - start`. It includes the start, but does not include the stop.

So for example the feature represented by:

```
chr1  1  5
```

includes 1, 2, 3, and 4 (but not 5) so it has a length of 5-1=4.

See [detailed writeup from UCSC](https://genome-blog.gi.ucsc.edu/blog/2016/12/12/the-ucsc-genome-browser-coordinate-counting-systems) for more.
