### ISSUE TITLE
Iteration error on result of groupby

### ISSUE THREAD

**Issue by yarden** [daler/pybedtools#80]
Hi,

When I run `groupby` on a given BED, the result is not always a BED, but it's still extremely convenient to call `groupby` from pybedtools. When the result of `groupby` is not a true BED, it yields the following error when iterating through the result:

```
  File "cbedtools.pyx", line 686, in pybedtools.cbedtools.IntervalFile.file_type (pybedtools/cbedtools.cpp:8852)
  File "cbedtools.pyx", line 561, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cpp:7293)
pybedtools.cbedtools.MalformedBedLineError: Unable to detect format from ['ENSMUSG00000025903', 'chr1', '4822392', '4822427', '11', '+']
```

Here is a small test case that reproduces this problem:

```
import os
import pybedtools
bed = pybedtools.BedTool(os.path.expanduser("~/test.bed"))
c_cols = [1, 2, 3, 5, 6]
# Gene ID
group_cols = [7]
# Operation columns: get comma-separated list of clusters
# including potential duplicates
ops_cols = len(c_cols) * ["collapse"]
grouped_bed = bed.groupby(g=group_cols, c=c_cols, ops=ops_cols)
print "Grouped without a problem.", grouped_bed
print "Now iterating:"
for line in grouped_bed:
    print line.fields
```

`test.bed` is:

```
chr1    4822392 4822427 180 11  +   ENSMUSG00000025903
chr1    4848367 4848399 196 12  +   ENSMUSG00000025903,ENSMUSG00000033813
chr1    5088389 5088423 221 12  +   ENSMUSG00000033793
chr1    6797675 6797720 383 13  +   ENSMUSG00000033740
chr1    7160723 7160752 420 24  +   ENSMUSG00000051285
chr1    9902237 9902267 671 16  +   ENSMUSG00000046101
chr1    10055420    10055451    707 11  +   ENSMUSG00000056763
chr1    11131981    11132014    827 31  +   ENSMUSG00000048960
chr1    13335253    13335284    1109    14  -   ENSMUSG00000005886
chr1    14277180    14277209    1216    28  -   ENSMUSG00000025932
```

Is there a way to iterate through a `BedTool` even though it's malformed? Or access a `BedTool` as a generator of lists that can then be converted to something else (like a numpy array)? I totally understand that there's no need to support non-BED files so I just want to extract the `groupby` result and then treat it as a different non-BED format.  Thanks!

**Comment by carissableker** [comment]
Is there a "smart" way to get a bed format back from this `groupyby`? 

```python
bed.groupby(
    g=[9], 
    c=[1,        2,      3,       4,     5,      6,       7,       8,      9], 
    o=['first', 'first', 'first', 'min', 'max', 'first', 'first', 'first', 'first'], 
)
```
Result:
```
ID=AT1G01010;	Chr1	Araport11	five_prime_UTR	1131	6130	.	+	.	ID=AT1G01010;
ID=AT1G01020;	Chr1	Araport11	five_prime_UTR	5965	11630	.	-	.	ID=AT1G01020;
ID=AT1G01030;	Chr1	Araport11	five_prime_UTR	10674	16214	.	-	.	ID=AT1G01030;
ID=AT1G01040;	Chr1	Araport11	five_prime_UTR	20621	25915	.	+	.	ID=AT1G01040;
ID=AT1G01050;	Chr1	Araport11	five_prime_UTR	30510	35671	.	-	.	ID=AT1G01050;
ID=AT1G01060;	Chr1	Araport11	five_prime_UTR	34422	40371	.	-	.	ID=AT1G01060;
ID=AT1G01070;	Chr1	Araport11	five_prime_UTR	38446	43517	.	-	.	ID=AT1G01070;
ID=AT1G01080;	Chr1	Araport11	five_prime_UTR	44520	49559	.	-	.	ID=AT1G01080;
ID=AT1G01090;	Chr1	Araport11	five_prime_UTR	46805	51804	.	-	.	ID=AT1G01090;
ID=AT1G01100;	Chr1	Araport11	five_prime_UTR	48464	53710	.	-	.	ID=AT1G01100;
```


Aside from the grouping column (first column in the output), the output should be valid bed, but when I tried to use `cut` to remove the first column, I got the same `MalformedBedLineError` error as in this issue. (As an aside,  this was not obvious to me, as the documentation for `cut` says "returns a BedTool of results [...] indexes returned must be valid GFF/GTF/BED/SAM features", not that the *input* needs to be valid features). 

I can use the `reformat` code given above, but maybe there is a more straight forward solution?

**Comment by daler** [comment]
Hmm, I suppose the `cut` method could be changed to accept arbitrary input, but it's currently set up to accept GTF/GFF fields as well as integers -- which does require correctly-formatted input.

Maybe something like this, where `assume_valid_input=False` would trigger a naive approach like `reformat()` above?

```python
def cut(self, indexes, stream=False, assume_valid_input=True):
    ...
```
